NJD Films Greenhouse Management System: DecorativePotDecorator Class Reference
DecorativePotDecorator Class Reference
Adds a decorative pot to a plant product.
#include <DecorativePotDecorator.h>
Public Member Functions
DecorativePotDecorator ()
DecorativePotDecorator (PlantProduct *product, const std::string &type="ceramic", const std::string &color="white")
virtual ~DecorativePotDecorator ()
double getPrice () const override
std::string getDescription () const override
void display () const override
std::string getPotType () const
void setPotType (const std::string &type)
std::string getPotColor () const
void setPotColor (const std::string &color)
double getPotPrice () const
Public Member Functions inherited from PlantDecorator
PlantDecorator ()
PlantDecorator (PlantProduct *product)
virtual ~PlantDecorator ()
PlantProduct * getWrappedProduct () const
void setWrappedProduct (PlantProduct *product)
Public Member Functions inherited from PlantProduct
PlantProduct ()
PlantProduct (Plant *p)
virtual ~PlantProduct ()
Plant * getPlant () const
void setPlant (Plant *p)
Private Attributes
std::string potType
std::string potColor
double potPrice
Additional Inherited Members
Protected Attributes inherited from PlantDecorator
PlantProduct * wrappedProduct
Protected Attributes inherited from PlantProduct
Plant * plant
Detailed Description
Adds a decorative pot to a plant product.
Available pot types: ceramic, terracotta, modern, vintage
Definition at line 12 of file DecorativePotDecorator.h.
Constructor & Destructor Documentation
DecorativePotDecorator() [1/2]
DecorativePotDecorator::DecorativePotDecorator ()
Definition at line 5 of file DecorativePotDecorator.cpp.
DecorativePotDecorator() [2/2]
DecorativePotDecorator::DecorativePotDecorator (PlantProduct * product, const std::string & type = "ceramic", const std::string & color = "white")
Definition at line 8 of file DecorativePotDecorator.cpp.
References potPrice.
~DecorativePotDecorator()
DecorativePotDecorator::~DecorativePotDecorator () virtual
Definition at line 21 of file DecorativePotDecorator.cpp.
Member Function Documentation
display()
void DecorativePotDecorator::display () const override virtual
Reimplemented from PlantDecorator.
Definition at line 33 of file DecorativePotDecorator.cpp.
References PlantProduct::getDescription(), PlantProduct::getPrice(), getPrice(), potColor, potPrice, potType, and PlantDecorator::wrappedProduct.
getDescription()
std::string DecorativePotDecorator::getDescription () const override virtual
Implements PlantDecorator.
Definition at line 28 of file DecorativePotDecorator.cpp.
References PlantProduct::getDescription(), potColor, potType, and PlantDecorator::wrappedProduct.
getPotColor()
std::string DecorativePotDecorator::getPotColor () const
Definition at line 55 of file DecorativePotDecorator.cpp.
References potColor.
getPotPrice()
double DecorativePotDecorator::getPotPrice () const
Definition at line 58 of file DecorativePotDecorator.cpp.
References potPrice.
getPotType()
std::string DecorativePotDecorator::getPotType () const
Definition at line 52 of file DecorativePotDecorator.cpp.
References potType.
getPrice()
double DecorativePotDecorator::getPrice () const override virtual
Implements PlantDecorator.
Definition at line 23 of file DecorativePotDecorator.cpp.
References PlantProduct::getPrice(), potPrice, and PlantDecorator::wrappedProduct.
Referenced by display().
setPotColor()
void DecorativePotDecorator::setPotColor (const std::string & color)
Definition at line 56 of file DecorativePotDecorator.cpp.
References potColor.
setPotType()
void DecorativePotDecorator::setPotType (const std::string & type)
Definition at line 53 of file DecorativePotDecorator.cpp.
References potType.
Member Data Documentation
potColor
std::string DecorativePotDecorator::potColor private
Definition at line 15 of file DecorativePotDecorator.h.
Referenced by display(), getDescription(), getPotColor(), and setPotColor().
potPrice
double DecorativePotDecorator::potPrice private
Definition at line 16 of file DecorativePotDecorator.h.
Referenced by DecorativePotDecorator(), display(), getPotPrice(), and getPrice().
potType
std::string DecorativePotDecorator::potType private
Definition at line 14 of file DecorativePotDecorator.h.
Referenced by display(), getDescription(), getPotType(), and setPotType().
The documentation for this class was generated from the following files:
Decorator - Plant Decoration/DecorativePotDecorator.h
Decorator - Plant Decoration/DecorativePotDecorator.cpp