NJD Films Greenhouse Management System: FloweringState Class Reference
FloweringState Class Reference
Represents the flowering state in a plant's lifecycle.
#include <FloweringState.h>
Public Member Functions
virtual ~FloweringState ()=default
Virtual destructor.
void water (PlantContext *context) override
Water the flowering plant carefully.
void fertilize (PlantContext *context) override
Apply bloom-supporting fertilizer.
void checkHealth (PlantContext *context) override
Check plant health and bloom condition.
std::string getStateName () const override
Get the state name.
Public Member Functions inherited from PlantState
virtual ~PlantState ()=default
Virtual destructor.
Detailed Description
Represents the flowering state in a plant's lifecycle.
The flowering state is when plants produce blooms. This is often the peak of the plant's visual appeal and requires careful maintenance to prolong the flowering period. After flowering completes, plants may enter DormantState or cycle back depending on the species.
Definition at line 21 of file FloweringState.h.
Constructor & Destructor Documentation
~FloweringState()
virtual FloweringState::~FloweringState () virtual default
Virtual destructor.
Member Function Documentation
checkHealth()
void FloweringState::checkHealth (PlantContext * context) override virtual
Check plant health and bloom condition.
Parameters
context Pointer to the PlantContext
Monitors bloom health and determines when flowering period ends.
Implements PlantState.
Definition at line 19 of file FloweringState.cpp.
fertilize()
void FloweringState::fertilize (PlantContext * context) override virtual
Apply bloom-supporting fertilizer.
Parameters
context Pointer to the PlantContext
Flowering plants benefit from specialized fertilization to support blooms.
Implements PlantState.
Definition at line 12 of file FloweringState.cpp.
References PlantContext::getPlant(), and Plant::modifyHealth().
getStateName()
std::string FloweringState::getStateName () const inline override virtual
Get the state name.
Returns
String "Flowering"
Implements PlantState.
Definition at line 57 of file FloweringState.h.
water()
void FloweringState::water (PlantContext * context) override virtual
Water the flowering plant carefully.
Parameters
context Pointer to the PlantContext
Flowering plants need consistent watering to maintain blooms. Proper watering extends the flowering period.
Implements PlantState.
Definition at line 5 of file FloweringState.cpp.
References PlantContext::getPlant(), and Plant::modifyHealth().
The documentation for this class was generated from the following files:
State - Plant lifecycle/FloweringState.h
State - Plant lifecycle/FloweringState.cpp