NJD Films Greenhouse Management System: GreenhouseController Class Reference
GreenhouseController Class Reference
Controller for greenhouse operations.
#include <GreenhouseController.h>
Public Member Functions
GreenhouseController (ModernWateringSystem *system, GreenhouseComponent *greenhouseComp)
Constructor.
~GreenhouseController ()
Destructor.
void performDailyMaintenance ()
Perform daily maintenance routine.
void waterGreenhouse ()
Water all plants in the greenhouse.
void changeSeason (const std::string &season)
Change the current season.
std::string getCurrentSeason () const
Get current season.
void displayGreenhouseStatus () const
Display greenhouse status.
std::string getSystemStatus () const
Get system status.
Private Attributes
ModernWateringSystem * wateringSystem
GreenhouseComponent * greenhouse
std::string currentSeason
Detailed Description
Controller for greenhouse operations.
Uses ModernWateringSystem interface (doesn't know about legacy system) This demonstrates how the adapter allows old and new systems to work together
Definition at line 16 of file GreenhouseController.h.
Constructor & Destructor Documentation
GreenhouseController()
GreenhouseController::GreenhouseController (ModernWateringSystem * system, GreenhouseComponent * greenhouseComp)
Constructor.
Parameters
system Pointer to watering system (could be adapter or modern system)
greenhouseComp Pointer to greenhouse component
Definition at line 5 of file GreenhouseController.cpp.
References ModernWateringSystem::adjustForSeason(), currentSeason, and wateringSystem.
~GreenhouseController()
GreenhouseController::~GreenhouseController ()
Destructor.
Definition at line 14 of file GreenhouseController.cpp.
Member Function Documentation
changeSeason()
void GreenhouseController::changeSeason (const std::string & season)
Change the current season.
Parameters
season New season
Definition at line 43 of file GreenhouseController.cpp.
References ModernWateringSystem::adjustForSeason(), currentSeason, greenhouse, and wateringSystem.
displayGreenhouseStatus()
void GreenhouseController::displayGreenhouseStatus () const
Display greenhouse status.
Definition at line 67 of file GreenhouseController.cpp.
References currentSeason, GreenhouseComponent::display(), and greenhouse.
getCurrentSeason()
std::string GreenhouseController::getCurrentSeason () const
Get current season.
Returns
Current season
Definition at line 62 of file GreenhouseController.cpp.
References currentSeason.
getSystemStatus()
std::string GreenhouseController::getSystemStatus () const
Get system status.
Returns
Status string
Definition at line 85 of file GreenhouseController.cpp.
References ModernWateringSystem::getSystemStatus(), and wateringSystem.
performDailyMaintenance()
void GreenhouseController::performDailyMaintenance ()
Perform daily maintenance routine.
Definition at line 19 of file GreenhouseController.cpp.
References currentSeason, greenhouse, and waterGreenhouse().
waterGreenhouse()
void GreenhouseController::waterGreenhouse ()
Water all plants in the greenhouse.
Definition at line 37 of file GreenhouseController.cpp.
References greenhouse, ModernWateringSystem::waterGreenhouse(), and wateringSystem.
Referenced by performDailyMaintenance().
Member Data Documentation
currentSeason
std::string GreenhouseController::currentSeason private
Definition at line 21 of file GreenhouseController.h.
Referenced by changeSeason(), displayGreenhouseStatus(), getCurrentSeason(), GreenhouseController(), and performDailyMaintenance().
greenhouse
GreenhouseComponent* GreenhouseController::greenhouse private
Definition at line 20 of file GreenhouseController.h.
Referenced by changeSeason(), displayGreenhouseStatus(), performDailyMaintenance(), and waterGreenhouse().
wateringSystem
ModernWateringSystem* GreenhouseController::wateringSystem private
Definition at line 19 of file GreenhouseController.h.
Referenced by changeSeason(), getSystemStatus(), GreenhouseController(), and waterGreenhouse().
The documentation for this class was generated from the following files:
Adapter - Legacy Watering System/GreenhouseController.h
Adapter - Legacy Watering System/GreenhouseController.cpp