NJD Films Greenhouse Management System: InventoryIterator Class Reference
InventoryIterator Class Reference
#include <InventoryIterator.h>
Public Member Functions
InventoryIterator (GreenhouseInventory *inv)
virtual ~InventoryIterator ()=default
void first () override
void next () override
bool isDone () const override
Plant * currentItem () const override
Public Member Functions inherited from PlantIterator
virtual ~PlantIterator ()=default
Private Attributes
GreenhouseInventory * inventory
size_t currentIndex
std::vector< Plant * > plants
Detailed Description
Definition at line 9 of file InventoryIterator.h.
Constructor & Destructor Documentation
InventoryIterator()
InventoryIterator::InventoryIterator (GreenhouseInventory * inv)
Definition at line 5 of file InventoryIterator.cpp.
References GreenhouseInventory::getCount(), GreenhouseInventory::getPlantAt(), inventory, and plants.
~InventoryIterator()
virtual InventoryIterator::~InventoryIterator () virtual default
Member Function Documentation
currentItem()
Plant * InventoryIterator::currentItem () const override virtual
Implements PlantIterator.
Definition at line 30 of file InventoryIterator.cpp.
References currentIndex, isDone(), and plants.
first()
void InventoryIterator::first () override virtual
Implements PlantIterator.
Definition at line 16 of file InventoryIterator.cpp.
References currentIndex.
isDone()
bool InventoryIterator::isDone () const override virtual
Implements PlantIterator.
Definition at line 26 of file InventoryIterator.cpp.
References currentIndex, and plants.
Referenced by currentItem(), and next().
next()
void InventoryIterator::next () override virtual
Implements PlantIterator.
Definition at line 20 of file InventoryIterator.cpp.
References currentIndex, and isDone().
Member Data Documentation
currentIndex
size_t InventoryIterator::currentIndex private
Definition at line 12 of file InventoryIterator.h.
Referenced by currentItem(), first(), isDone(), and next().
inventory
GreenhouseInventory* InventoryIterator::inventory private
Definition at line 11 of file InventoryIterator.h.
Referenced by InventoryIterator().
plants
std::vector<Plant*> InventoryIterator::plants private
Definition at line 13 of file InventoryIterator.h.
Referenced by currentItem(), InventoryIterator(), and isDone().
The documentation for this class was generated from the following files:
Iterator - Inventory Management/InventoryIterator.h
Iterator - Inventory Management/InventoryIterator.cpp