NJD Films Greenhouse Management System: SeedlingState Class Reference
SeedlingState Class Reference
Represents the seedling state in a plant's lifecycle.
#include <SeedlingState.h>
Public Member Functions
virtual ~SeedlingState ()=default
Virtual destructor.
void water (PlantContext *context) override
Water the seedling gently.
void fertilize (PlantContext *context) override
Apply minimal fertilizer appropriate for seedlings.
void checkHealth (PlantContext *context) override
Check seedling health and growth progress.
std::string getStateName () const override
Get the state name.
Public Member Functions inherited from PlantState
virtual ~PlantState ()=default
Virtual destructor.
Detailed Description
Represents the seedling state in a plant's lifecycle.
This is the initial growth stage where plants are fragile and require gentle care. Seedlings need careful watering and minimal fertilization. After sufficient growth, they transition to the GrowingState.
Definition at line 20 of file SeedlingState.h.
Constructor & Destructor Documentation
~SeedlingState()
virtual SeedlingState::~SeedlingState () virtual default
Virtual destructor.
Member Function Documentation
checkHealth()
void SeedlingState::checkHealth (PlantContext * context) override virtual
Check seedling health and growth progress.
Parameters
context Pointer to the PlantContext
Monitors if the seedling is ready to transition to growing state.
Implements PlantState.
Definition at line 20 of file SeedlingState.cpp.
References Plant::getHealthLevel(), PlantContext::getPlant(), and PlantContext::setState().
fertilize()
void SeedlingState::fertilize (PlantContext * context) override virtual
Apply minimal fertilizer appropriate for seedlings.
Parameters
context Pointer to the PlantContext
Seedlings need very light fertilization as they are sensitive.
Implements PlantState.
Definition at line 13 of file SeedlingState.cpp.
References PlantContext::getPlant(), and Plant::modifyHealth().
getStateName()
std::string SeedlingState::getStateName () const inline override virtual
Get the state name.
Returns
String "Seedling"
Implements PlantState.
Definition at line 56 of file SeedlingState.h.
water()
void SeedlingState::water (PlantContext * context) override virtual
Water the seedling gently.
Parameters
context Pointer to the PlantContext
Seedlings require gentle watering to avoid drowning. Proper watering contributes to transition to growing state.
Implements PlantState.
Definition at line 6 of file SeedlingState.cpp.
References PlantContext::getPlant(), and Plant::modifyHealth().
The documentation for this class was generated from the following files:
State - Plant lifecycle/SeedlingState.h
State - Plant lifecycle/SeedlingState.cpp