NJD Films Greenhouse Management System: MatureState Class Reference
MatureState Class Reference
Represents the mature state in a plant's lifecycle.
#include <MatureState.h>
Public Member Functions
virtual ~MatureState ()=default
Virtual destructor.
void water (PlantContext *context) override
Water the mature plant with maintenance amounts.
void fertilize (PlantContext *context) override
Apply maintenance fertilizer.
void checkHealth (PlantContext *context) override
Check plant health and readiness for flowering.
std::string getStateName () const override
Get the state name.
Public Member Functions inherited from PlantState
virtual ~PlantState ()=default
Virtual destructor.
Detailed Description
Represents the mature state in a plant's lifecycle.
In the mature state, plants have reached their full size and are stable. They require maintenance-level care with moderate watering and occasional fertilization. Under proper conditions, they may transition to FloweringState.
Definition at line 20 of file MatureState.h.
Constructor & Destructor Documentation
~MatureState()
virtual MatureState::~MatureState () virtual default
Virtual destructor.
Member Function Documentation
checkHealth()
void MatureState::checkHealth (PlantContext * context) override virtual
Check plant health and readiness for flowering.
Parameters
context Pointer to the PlantContext
Monitors plant condition and determines if ready to flower.
Implements PlantState.
Definition at line 19 of file MatureState.cpp.
fertilize()
void MatureState::fertilize (PlantContext * context) override virtual
Apply maintenance fertilizer.
Parameters
context Pointer to the PlantContext
Mature plants need less frequent fertilization to maintain health.
Implements PlantState.
Definition at line 12 of file MatureState.cpp.
References PlantContext::getPlant(), and Plant::modifyHealth().
getStateName()
std::string MatureState::getStateName () const inline override virtual
Get the state name.
Returns
String "Mature"
Implements PlantState.
Definition at line 56 of file MatureState.h.
water()
void MatureState::water (PlantContext * context) override virtual
Water the mature plant with maintenance amounts.
Parameters
context Pointer to the PlantContext
Mature plants need consistent but not excessive watering. Proper care may trigger flowering in appropriate species.
Implements PlantState.
Definition at line 5 of file MatureState.cpp.
References PlantContext::getPlant(), and Plant::modifyHealth().
The documentation for this class was generated from the following files:
State - Plant lifecycle/MatureState.h
State - Plant lifecycle/MatureState.cpp