NJD Films Greenhouse Management System: ModernWateringSystem Class Reference
ModernWateringSystem Class Reference abstract
Modern watering system interface (Target)
#include <ModernWateringSystem.h>
Public Member Functions
virtual ~ModernWateringSystem ()
Virtual destructor.
virtual void waterGreenhouse (GreenhouseComponent *greenhouse)=0
Water greenhouse components automatically.
virtual void adjustForSeason (const std::string &season)=0
Adjust watering based on season.
virtual std::string getSystemStatus ()=0
Check system status.
Detailed Description
Modern watering system interface (Target)
This is the interface that GreenhouseController expects to use
Definition at line 14 of file ModernWateringSystem.h.
Constructor & Destructor Documentation
~ModernWateringSystem()
virtual ModernWateringSystem::~ModernWateringSystem () inline virtual
Virtual destructor.
Definition at line 20 of file ModernWateringSystem.h.
Member Function Documentation
adjustForSeason()
virtual void ModernWateringSystem::adjustForSeason (const std::string & season) pure virtual
Adjust watering based on season.
Parameters
season Current season
Implemented in WateringAdapter.
Referenced by GreenhouseController::changeSeason(), and GreenhouseController::GreenhouseController().
getSystemStatus()
virtual std::string ModernWateringSystem::getSystemStatus () pure virtual
Check system status.
Returns
Status message
Implemented in WateringAdapter.
Referenced by GreenhouseController::getSystemStatus().
waterGreenhouse()
virtual void ModernWateringSystem::waterGreenhouse (GreenhouseComponent * greenhouse) pure virtual
Water greenhouse components automatically.
Parameters
greenhouse Pointer to greenhouse component to water
Implemented in WateringAdapter.
Referenced by GreenhouseController::waterGreenhouse().
The documentation for this class was generated from the following file:
Adapter - Legacy Watering System/ModernWateringSystem.h