NJD Films Greenhouse Management System: PlantArrangementBuilder Class Reference
PlantArrangementBuilder Class Reference abstract
#include <PlantArrangementBuilder.h>
Public Member Functions
PlantArrangementBuilder ()
virtual ~PlantArrangementBuilder ()
virtual void reset ()=0
virtual void setBasicInfo ()=0
virtual void selectContainer ()=0
virtual void addPlants ()=0
virtual void addDecorations ()=0
virtual void calculatePrice ()=0
PlantArrangement * getArrangement ()
Protected Attributes
PlantArrangement * arrangement
Detailed Description
Definition at line 7 of file PlantArrangementBuilder.h.
Constructor & Destructor Documentation
PlantArrangementBuilder()
PlantArrangementBuilder::PlantArrangementBuilder ()
Definition at line 4 of file PlantArrangementBuilder.cpp.
~PlantArrangementBuilder()
PlantArrangementBuilder::~PlantArrangementBuilder () virtual
Definition at line 6 of file PlantArrangementBuilder.cpp.
Member Function Documentation
addDecorations()
virtual void PlantArrangementBuilder::addDecorations () pure virtual
Implemented in LandscapeArrangementBuilder, and GiftArrangementBuilder.
Referenced by ArrangementDirector::constructCustomArrangement(), and ArrangementDirector::constructDeluxeArrangement().
addPlants()
virtual void PlantArrangementBuilder::addPlants () pure virtual
Implemented in LandscapeArrangementBuilder, and GiftArrangementBuilder.
Referenced by ArrangementDirector::constructCustomArrangement(), ArrangementDirector::constructDeluxeArrangement(), and ArrangementDirector::constructSimpleArrangement().
calculatePrice()
virtual void PlantArrangementBuilder::calculatePrice () pure virtual
Implemented in LandscapeArrangementBuilder, and GiftArrangementBuilder.
Referenced by ArrangementDirector::constructCustomArrangement(), ArrangementDirector::constructDeluxeArrangement(), and ArrangementDirector::constructSimpleArrangement().
getArrangement()
PlantArrangement * PlantArrangementBuilder::getArrangement ()
Definition at line 10 of file PlantArrangementBuilder.cpp.
References arrangement.
Referenced by ArrangementDirector::constructCustomArrangement(), ArrangementDirector::constructDeluxeArrangement(), and ArrangementDirector::constructSimpleArrangement().
reset()
virtual void PlantArrangementBuilder::reset () pure virtual
Implemented in LandscapeArrangementBuilder, and GiftArrangementBuilder.
Referenced by ArrangementDirector::constructCustomArrangement(), ArrangementDirector::constructDeluxeArrangement(), and ArrangementDirector::constructSimpleArrangement().
selectContainer()
virtual void PlantArrangementBuilder::selectContainer () pure virtual
Implemented in LandscapeArrangementBuilder, and GiftArrangementBuilder.
Referenced by ArrangementDirector::constructCustomArrangement(), ArrangementDirector::constructDeluxeArrangement(), and ArrangementDirector::constructSimpleArrangement().
setBasicInfo()
virtual void PlantArrangementBuilder::setBasicInfo () pure virtual
Implemented in LandscapeArrangementBuilder, and GiftArrangementBuilder.
Referenced by ArrangementDirector::constructCustomArrangement(), ArrangementDirector::constructDeluxeArrangement(), and ArrangementDirector::constructSimpleArrangement().
Member Data Documentation
arrangement
PlantArrangement* PlantArrangementBuilder::arrangement protected
Definition at line 9 of file PlantArrangementBuilder.h.
Referenced by GiftArrangementBuilder::addPlants(), LandscapeArrangementBuilder::addPlants(), GiftArrangementBuilder::calculatePrice(), LandscapeArrangementBuilder::calculatePrice(), getArrangement(), GiftArrangementBuilder::reset(), LandscapeArrangementBuilder::reset(), GiftArrangementBuilder::selectContainer(), LandscapeArrangementBuilder::selectContainer(), GiftArrangementBuilder::setBasicInfo(), and LandscapeArrangementBuilder::setBasicInfo().
The documentation for this class was generated from the following files:
Builder - Plant Bundle Creator/PlantArrangementBuilder.h
Builder - Plant Bundle Creator/PlantArrangementBuilder.cpp