NJD Films Greenhouse Management System: LandscapeArrangementBuilder Class Reference
LandscapeArrangementBuilder Class Reference
#include <LandscapeArrangementBuilder.h>
Public Member Functions
LandscapeArrangementBuilder ()
virtual ~LandscapeArrangementBuilder ()
void setAvailablePlants (const std::vector< Plant * > &plants)
void setTheme (const std::string &theme)
void reset () override
void setBasicInfo () override
void selectContainer () override
void addPlants () override
void addDecorations () override
void calculatePrice () override
Public Member Functions inherited from PlantArrangementBuilder
PlantArrangementBuilder ()
virtual ~PlantArrangementBuilder ()
PlantArrangement * getArrangement ()
Private Attributes
std::vector< Plant * > availablePlants
std::string landscapeTheme
Additional Inherited Members
Protected Attributes inherited from PlantArrangementBuilder
PlantArrangement * arrangement
Detailed Description
Definition at line 10 of file LandscapeArrangementBuilder.h.
Constructor & Destructor Documentation
LandscapeArrangementBuilder()
LandscapeArrangementBuilder::LandscapeArrangementBuilder ()
Definition at line 6 of file LandscapeArrangementBuilder.cpp.
~LandscapeArrangementBuilder()
LandscapeArrangementBuilder::~LandscapeArrangementBuilder () virtual
Definition at line 9 of file LandscapeArrangementBuilder.cpp.
Member Function Documentation
addDecorations()
void LandscapeArrangementBuilder::addDecorations () override virtual
Implements PlantArrangementBuilder.
Definition at line 47 of file LandscapeArrangementBuilder.cpp.
addPlants()
void LandscapeArrangementBuilder::addPlants () override virtual
Implements PlantArrangementBuilder.
Definition at line 35 of file LandscapeArrangementBuilder.cpp.
References PlantArrangement::addPlant(), PlantArrangementBuilder::arrangement, and availablePlants.
calculatePrice()
void LandscapeArrangementBuilder::calculatePrice () override virtual
Implements PlantArrangementBuilder.
Definition at line 55 of file LandscapeArrangementBuilder.cpp.
References PlantArrangementBuilder::arrangement, and PlantArrangement::setBasePrice().
reset()
void LandscapeArrangementBuilder::reset () override virtual
Implements PlantArrangementBuilder.
Definition at line 19 of file LandscapeArrangementBuilder.cpp.
References PlantArrangementBuilder::arrangement.
selectContainer()
void LandscapeArrangementBuilder::selectContainer () override virtual
Implements PlantArrangementBuilder.
Definition at line 30 of file LandscapeArrangementBuilder.cpp.
References PlantArrangementBuilder::arrangement, and PlantArrangement::setContainerType().
setAvailablePlants()
void LandscapeArrangementBuilder::setAvailablePlants (const std::vector< Plant * > & plants)
Definition at line 11 of file LandscapeArrangementBuilder.cpp.
References availablePlants.
setBasicInfo()
void LandscapeArrangementBuilder::setBasicInfo () override virtual
Implements PlantArrangementBuilder.
Definition at line 24 of file LandscapeArrangementBuilder.cpp.
References PlantArrangementBuilder::arrangement, landscapeTheme, PlantArrangement::setDescription(), and PlantArrangement::setName().
setTheme()
void LandscapeArrangementBuilder::setTheme (const std::string & theme)
Definition at line 15 of file LandscapeArrangementBuilder.cpp.
References landscapeTheme.
Member Data Documentation
availablePlants
std::vector<Plant*> LandscapeArrangementBuilder::availablePlants private
Definition at line 12 of file LandscapeArrangementBuilder.h.
Referenced by addPlants(), and setAvailablePlants().
landscapeTheme
std::string LandscapeArrangementBuilder::landscapeTheme private
Definition at line 13 of file LandscapeArrangementBuilder.h.
Referenced by setBasicInfo(), and setTheme().
The documentation for this class was generated from the following files:
Builder - Plant Bundle Creator/LandscapeArrangementBuilder.h
Builder - Plant Bundle Creator/LandscapeArrangementBuilder.cpp