NJD Films Greenhouse Management System: PlantContext Class Reference
PlantContext Class Reference
Context class that maintains the current state and delegates operations to it.
#include <PlantContext.h>
Public Member Functions
PlantContext (Plant *p)
Constructor that initializes the context with a plant.
virtual ~PlantContext ()
Destructor that cleans up the current state.
void setState (PlantState *state)
Set a new state (transitions to a new lifecycle state)
PlantState * getCurrentState () const
Get the current state.
void water ()
Delegate watering operation to the current state.
void fertilize ()
Delegate fertilizing operation to the current state.
void checkHealth ()
Delegate health check operation to the current state.
Plant * getPlant () const
Get the plant being managed.
Private Attributes
PlantState * currentState
Pointer to the current state.
Plant * plant
Pointer to the plant being managed.
std::vector< Plant * > plants
Collection of plants (for batch operations)
Detailed Description
Context class that maintains the current state and delegates operations to it.
This class is part of the State design pattern implementation. It holds a reference to the current PlantState object and delegates state-specific behavior to it. The context allows for dynamic state transitions during the plant's lifecycle.
Definition at line 21 of file PlantContext.h.
Constructor & Destructor Documentation
PlantContext()
PlantContext::PlantContext (Plant * p) inline
Constructor that initializes the context with a plant.
Parameters
p Pointer to the plant to be managed
Definition at line 32 of file PlantContext.h.
~PlantContext()
virtual PlantContext::~PlantContext () inline virtual
Destructor that cleans up the current state.
Definition at line 37 of file PlantContext.h.
References currentState.
Member Function Documentation
checkHealth()
void PlantContext::checkHealth () inline
Delegate health check operation to the current state.
Calls the checkHealth() method on the current state if one exists.
Definition at line 72 of file PlantContext.h.
References PlantState::checkHealth(), and currentState.
fertilize()
void PlantContext::fertilize () inline
Delegate fertilizing operation to the current state.
Calls the fertilize() method on the current state if one exists.
Definition at line 65 of file PlantContext.h.
References currentState, and PlantState::fertilize().
getCurrentState()
PlantState* PlantContext::getCurrentState () const inline
Get the current state.
Returns
Pointer to the current PlantState
Definition at line 51 of file PlantContext.h.
References currentState.
getPlant()
Plant* PlantContext::getPlant () const inline
Get the plant being managed.
Returns
Pointer to the Plant object
Definition at line 78 of file PlantContext.h.
References plant.
Referenced by GrowingState::checkHealth(), SeedlingState::checkHealth(), FloweringState::fertilize(), GrowingState::fertilize(), MatureState::fertilize(), SeedlingState::fertilize(), DormantState::water(), FloweringState::water(), GrowingState::water(), MatureState::water(), and SeedlingState::water().
setState()
void PlantContext::setState (PlantState * state) inline
Set a new state (transitions to a new lifecycle state)
Parameters
state Pointer to the new PlantState to transition to
Deletes the current state and replaces it with the new one.
Definition at line 45 of file PlantContext.h.
References currentState.
Referenced by GrowingState::checkHealth(), and SeedlingState::checkHealth().
water()
void PlantContext::water () inline
Delegate watering operation to the current state.
Calls the water() method on the current state if one exists.
Definition at line 58 of file PlantContext.h.
References currentState, and PlantState::water().
Member Data Documentation
currentState
PlantState* PlantContext::currentState private
Pointer to the current state.
Definition at line 23 of file PlantContext.h.
Referenced by checkHealth(), fertilize(), getCurrentState(), setState(), water(), and ~PlantContext().
plant
Plant* PlantContext::plant private
Pointer to the plant being managed.
Definition at line 24 of file PlantContext.h.
Referenced by getPlant().
plants
std::vector<Plant*> PlantContext::plants private
Collection of plants (for batch operations)
Definition at line 25 of file PlantContext.h.
The documentation for this class was generated from the following file:
State - Plant lifecycle/PlantContext.h