NJD Films Greenhouse Management System: ArrangementDirector Class Reference
ArrangementDirector Class Reference
#include <ArrangementDirector.h>
Public Member Functions
ArrangementDirector ()
virtual ~ArrangementDirector ()
void setBuilder (PlantArrangementBuilder *builder)
PlantArrangement * constructSimpleArrangement ()
PlantArrangement * constructDeluxeArrangement ()
PlantArrangement * constructCustomArrangement (bool includeDecorations)
Private Attributes
PlantArrangementBuilder * builder
Detailed Description
Definition at line 7 of file ArrangementDirector.h.
Constructor & Destructor Documentation
ArrangementDirector()
ArrangementDirector::ArrangementDirector ()
Definition at line 6 of file ArrangementDirector.cpp.
~ArrangementDirector()
ArrangementDirector::~ArrangementDirector () virtual
Definition at line 8 of file ArrangementDirector.cpp.
Member Function Documentation
constructCustomArrangement()
PlantArrangement * ArrangementDirector::constructCustomArrangement (bool includeDecorations)
Definition at line 54 of file ArrangementDirector.cpp.
References PlantArrangementBuilder::addDecorations(), PlantArrangementBuilder::addPlants(), builder, PlantArrangementBuilder::calculatePrice(), PlantArrangementBuilder::getArrangement(), PlantArrangementBuilder::reset(), PlantArrangementBuilder::selectContainer(), and PlantArrangementBuilder::setBasicInfo().
constructDeluxeArrangement()
PlantArrangement * ArrangementDirector::constructDeluxeArrangement ()
Definition at line 35 of file ArrangementDirector.cpp.
References PlantArrangementBuilder::addDecorations(), PlantArrangementBuilder::addPlants(), builder, PlantArrangementBuilder::calculatePrice(), PlantArrangementBuilder::getArrangement(), PlantArrangementBuilder::reset(), PlantArrangementBuilder::selectContainer(), and PlantArrangementBuilder::setBasicInfo().
constructSimpleArrangement()
PlantArrangement * ArrangementDirector::constructSimpleArrangement ()
Definition at line 17 of file ArrangementDirector.cpp.
References PlantArrangementBuilder::addPlants(), builder, PlantArrangementBuilder::calculatePrice(), PlantArrangementBuilder::getArrangement(), PlantArrangementBuilder::reset(), PlantArrangementBuilder::selectContainer(), and PlantArrangementBuilder::setBasicInfo().
setBuilder()
void ArrangementDirector::setBuilder (PlantArrangementBuilder * builder)
Definition at line 12 of file ArrangementDirector.cpp.
References builder.
Member Data Documentation
builder
PlantArrangementBuilder* ArrangementDirector::builder private
Definition at line 9 of file ArrangementDirector.h.
Referenced by constructCustomArrangement(), constructDeluxeArrangement(), constructSimpleArrangement(), and setBuilder().
The documentation for this class was generated from the following files:
Builder - Plant Bundle Creator/ArrangementDirector.h
Builder - Plant Bundle Creator/ArrangementDirector.cpp