NJD Films Greenhouse Management System: PlantCareStaff Class Reference
PlantCareStaff Class Reference
#include <PlantCareStaff.h>
Public Member Functions
PlantCareStaff (const std::string &memberName="Plant Care Staff")
virtual ~PlantCareStaff ()=default
void performDuties () override
void waterPlants ()
void prunePlants ()
void fertilizePlants ()
Public Member Functions inherited from StaffMember
StaffMember (const std::string &memberName="Staff", const std::string &memberRole="General")
virtual ~StaffMember ()=default
std::string getName () const
std::string getRole () const
Additional Inherited Members
Protected Attributes inherited from StaffMember
std::string name
std::string role
Detailed Description
Definition at line 10 of file PlantCareStaff.h.
Constructor & Destructor Documentation
PlantCareStaff()
PlantCareStaff::PlantCareStaff (const std::string & memberName = "Plant Care Staff")
Definition at line 4 of file PlantCareStaff.cpp.
~PlantCareStaff()
virtual PlantCareStaff::~PlantCareStaff () virtual default
Member Function Documentation
fertilizePlants()
void PlantCareStaff::fertilizePlants ()
Definition at line 20 of file PlantCareStaff.cpp.
References StaffMember::name.
Referenced by FertilizePlantsCommand::execute().
performDuties()
void PlantCareStaff::performDuties () override virtual
Implements StaffMember.
Definition at line 8 of file PlantCareStaff.cpp.
References StaffMember::name.
prunePlants()
void PlantCareStaff::prunePlants ()
Definition at line 16 of file PlantCareStaff.cpp.
References StaffMember::name.
Referenced by PrunePlantsCommand::execute().
waterPlants()
void PlantCareStaff::waterPlants ()
Definition at line 12 of file PlantCareStaff.cpp.
References StaffMember::name.
Referenced by WaterPlantsCommand::execute().
The documentation for this class was generated from the following files:
Command - Staff Functions/PlantCareStaff.h
Command - Staff Functions/PlantCareStaff.cpp