NJD Films Greenhouse Management System: PlantState Class Reference
PlantState Class Reference abstract
Abstract state interface for plant lifecycle management.
#include <PlantState.h>
Public Member Functions
virtual ~PlantState ()=default
Virtual destructor.
virtual void water (PlantContext *context)=0
Water the plant based on current state.
virtual void fertilize (PlantContext *context)=0
Fertilize the plant based on current state.
virtual void checkHealth (PlantContext *context)=0
Check the health of the plant in current state.
virtual std::string getStateName () const =0
Get the name of the current state.
Detailed Description
Abstract state interface for plant lifecycle management.
This class implements the State design pattern, allowing plants to change behavior based on their current lifecycle state (seedling, growing, mature, etc.). Each concrete state provides specific implementations for watering, fertilizing, and health monitoring.
Definition at line 23 of file PlantState.h.
Constructor & Destructor Documentation
~PlantState()
virtual PlantState::~PlantState () virtual default
Virtual destructor.
Member Function Documentation
checkHealth()
void PlantState::checkHealth (PlantContext * context) pure virtual
Check the health of the plant in current state.
Parameters
context Pointer to the PlantContext managing this state
Performs state-specific health checks and may trigger state transitions.
Implemented in SeedlingState, MatureState, GrowingState, FloweringState, and DormantState.
Definition at line 13 of file PlantState.cpp.
Referenced by PlantContext::checkHealth().
fertilize()
void PlantState::fertilize (PlantContext * context) pure virtual
Fertilize the plant based on current state.
Parameters
context Pointer to the PlantContext managing this state
Different states have different fertilization needs. This method may trigger a state transition.
Implemented in SeedlingState, MatureState, GrowingState, FloweringState, and DormantState.
Definition at line 9 of file PlantState.cpp.
Referenced by PlantContext::fertilize().
getStateName()
virtual std::string PlantState::getStateName () const pure virtual
Get the name of the current state.
Returns
String representation of the state name
Implemented in SeedlingState, MatureState, GrowingState, FloweringState, and DormantState.
water()
void PlantState::water (PlantContext * context) pure virtual
Water the plant based on current state.
Parameters
context Pointer to the PlantContext managing this state
Different states may require different watering approaches. This method may trigger a state transition.
Implemented in SeedlingState, MatureState, GrowingState, FloweringState, and DormantState.
Definition at line 5 of file PlantState.cpp.
Referenced by PlantContext::water().
The documentation for this class was generated from the following files:
State - Plant lifecycle/PlantState.h
State - Plant lifecycle/PlantState.cpp