NJD Films Greenhouse Management System: Lavender Class Reference
Lavender Class Reference
Concrete plant class representing lavender.
#include <Lavendar.h>
Public Member Functions
Lavender ()
Default constructor.
Plant * clone () const override
Clone method for Prototype pattern.
std::string getType () const override
Get plant type.
virtual ~Lavender ()=default
Virtual destructor.
Lavender ()
Default constructor.
Lavender (const Lavender &other)
Copy constructor.
~Lavender () override
Destructor.
Plant * clone () const override
Create a clone of this lavender.
std::string getType () const override
Get the plant type.
void initialize () override
Initialize lavender-specific attributes.
void display () const override
Display lavender information.
Public Member Functions inherited from Plant
Plant ()
Default constructor.
Plant (int id, const std::string &species)
Constructor with ID and species.
virtual ~Plant ()
Virtual destructor.
Plant (const Plant &other)
Copy constructor for Prototype pattern.
int getPlantId () const
void setPlantId (int id)
std::string getSpecies () const
void setSpecies (const std::string &species)
std::string getScientificName () const
void setScientificName (const std::string &name)
int getAge () const
void incrementAge ()
double getHeight () const
void setHeight (double h)
void grow (double amount)
double getBasePrice () const
void setBasePrice (double price)
bool isReadyForSale () const
void setReadyForSale (bool ready)
int getHealthLevel () const
void setHealthLevel (int health)
void modifyHealth (int delta)
int getWateringFrequency () const
void setWateringFrequency (int days)
int getSunlightRequirement () const
void setSunlightRequirement (int hours)
int getFertilizingFrequency () const
void setFertilizingFrequency (int days)
std::string getSoilType () const
void setSoilType (const std::string &soil)
int getDaysToMaturity () const
void setDaysToMaturity (int days)
int getCurrentGrowthDays () const
void incrementGrowthDays ()
std::string getCurrentSeason () const
void setCurrentSeason (const std::string &season)
bool isMature () const
PlantCareRoutine * getCareRoutine () const
void setCareRoutine (PlantCareRoutine *routine)
void executeCareRoutine ()
Execute the template method care routine.
PlantContext * getContext () const
void setContext (PlantContext *ctx)
PlantState * getCurrentState () const
void setState (PlantState *state)
void transitionState ()
Trigger state transition.
PlantCareStrategy * getCareStrategy () const
void setCareStrategy (PlantCareStrategy *strategy)
void applyCareStrategy ()
Apply current care strategy.
void water ()
void fertilize ()
void prune ()
void inspect ()
std::string getLastWatered () const
void updateLastWatered (const std::string &timestamp)
std::string getLastFertilized () const
void updateLastFertilized (const std::string &timestamp)
std::string getLastPruned () const
void updateLastPruned (const std::string &timestamp)
int getTimesWatered () const
int getTimesFertilized () const
int getTimesPruned () const
std::string getLocation () const
void setLocation (const std::string &loc)
int getShelfNumber () const
void setShelfNumber (int shelf)
std::string getStateDescription () const
std::string getCareDescription () const
bool needsWater () const
bool needsFertilizer () const
bool needsPruning () const
bool isHealthy () const
bool needsAttention () const
void update ()
std::string serialize () const
void deserialize (const std::string &data)
Additional Inherited Members
Protected Member Functions inherited from Plant
Plant (const std::string &species, int daysToMaturity)
Protected constructor for derived classes.
Detailed Description
Concrete plant class representing lavender.
Lavender is a concrete implementation of Plant representing lavender herbs. Lavender is a fragrant herb requiring moderate watering, good sunlight, and sandy soil. Popular for herb gardens and aromatherapy arrangements.
Plant Characteristics:
Base Price: R85.00
Days to Maturity: 40 days
Watering: Every 5 days (moderate)
Sunlight: 7 hours/day (good sun)
Fertilizing: Every 30 days
Soil Type: Sandy
See also
Plant
Lavender is an aromatic herb known for its fragrant purple flowers and medicinal properties. It requires moderate watering, good drainage, and full sunlight. Popular for both ornamental and practical uses (essential oils, aromatherapy, cooking). Thrives in Mediterranean-like conditions.
Definition at line 31 of file Lavendar.h.
Constructor & Destructor Documentation
Lavender() [1/3]
Lavender::Lavender () inline
Default constructor.
Postcondition
Lavender initialized with species "Lavender", 40 days to maturity, R85 base price, 5-day watering, 7hr sunlight, sandy soil
Definition at line 38 of file Lavendar.h.
References Plant::Plant(), Plant::setBasePrice(), Plant::setFertilizingFrequency(), Plant::setSoilType(), Plant::setSunlightRequirement(), and Plant::setWateringFrequency().
Referenced by clone(), Lavender(), and Lavender().
~Lavender() [1/2]
Lavender::~Lavender () virtual default
Virtual destructor.
Definition at line 11 of file LavenderFactory.cpp.
Lavender() [2/3]
Lavender::Lavender ()
Default constructor.
Creates lavender with aromatic and Mediterranean characteristics.
References Lavender().
Lavender() [3/3]
Lavender::Lavender (const Lavender & other)
Copy constructor.
Parameters
other The Lavender to copy from
Definition at line 9 of file LavenderFactory.cpp.
References Lavender(), and Plant::Plant().
~Lavender() [2/2]
Lavender::~Lavender () override
Destructor.
Member Function Documentation
clone() [1/2]
Plant * Lavender::clone () const override virtual
Create a clone of this lavender.
Returns
Pointer to a new Lavender that is a copy of this one
Implements the Prototype pattern's clone method.
Implements Plant.
References Plant::Plant().
clone() [2/2]
Plant * Lavender::clone () const inline override virtual
Clone method for Prototype pattern.
Returns
Pointer to cloned Lavender object
Implements Plant.
Definition at line 50 of file Lavendar.h.
References Lavender(), and Plant::Plant().
display()
void Lavender::display () const override virtual
Display lavender information.
Outputs details about this lavender to the console.
Reimplemented from Plant.
Definition at line 36 of file LavenderFactory.cpp.
References Plant::display(), and Plant::getScientificName().
getType() [1/2]
std::string Lavender::getType () const override virtual
Get the plant type.
Returns
String "Lavender"
Implements Plant.
getType() [2/2]
std::string Lavender::getType () const inline override virtual
Get plant type.
Returns
"Lavender"
Implements Plant.
Definition at line 58 of file Lavendar.h.
initialize()
void Lavender::initialize () override virtual
Initialize lavender-specific attributes.
Sets up lavender-specific characteristics like moderate watering, full sun requirements, and aromatic properties.
Reimplemented from Plant.
Definition at line 23 of file LavenderFactory.cpp.
References Plant::setBasePrice(), Plant::setCurrentSeason(), Plant::setFertilizingFrequency(), Plant::setHealthLevel(), Plant::setHeight(), Plant::setScientificName(), Plant::setSoilType(), Plant::setSunlightRequirement(), and Plant::setWateringFrequency().
The documentation for this class was generated from the following files:
Plant - Abstract Base/Lavendar.h
Factory - Plant Creation/LavenderFactory.h
Factory - Plant Creation/LavenderFactory.cpp