NJD Films Greenhouse Management System: RosePrototype Class Reference
RosePrototype Class Reference
Concrete prototype implementation for rose propagation.
#include <RosePrototype.h>
Public Member Functions
RosePrototype ()
Default constructor.
RosePrototype (const RosePrototype &other)
Copy constructor.
virtual ~RosePrototype ()
Virtual destructor.
PlantPrototype * clone () override
Clone this rose prototype.
Public Member Functions inherited from PlantPrototype
PlantPrototype ()
Default constructor.
PlantPrototype (const PlantPrototype &other)
Copy constructor for cloning.
virtual ~PlantPrototype ()
Virtual destructor.
std::string getPlantType () const
Get the type/species of the plant.
int getPlantHealth () const
Get the health level of the plant.
void setPlantHealth (int h)
Set the health level of the plant.
Additional Inherited Members
Protected Attributes inherited from PlantPrototype
Plant * plant
Pointer to the plant being prototyped.
Detailed Description
Concrete prototype implementation for rose propagation.
This class implements the Prototype pattern for rose plants. Roses can be propagated through stem cuttings, and this prototype allows creating new rose plants from existing specimens. The clone() method creates a new RosePrototype with similar characteristics to the original.
Definition at line 20 of file RosePrototype.h.
Constructor & Destructor Documentation
RosePrototype() [1/2]
RosePrototype::RosePrototype ()
Default constructor.
Creates a new rose prototype with default characteristics.
Definition at line 10 of file RosePrototype.cpp.
References PlantPrototype::plant.
Referenced by clone(), and RosePrototype().
RosePrototype() [2/2]
RosePrototype::RosePrototype (const RosePrototype & other)
Copy constructor.
Parameters
other The RosePrototype to copy from
Creates a deep copy of another rose prototype, used internally during the cloning process.
Definition at line 14 of file RosePrototype.cpp.
References PlantPrototype::PlantPrototype(), and RosePrototype().
~RosePrototype()
RosePrototype::~RosePrototype () virtual
Virtual destructor.
Definition at line 18 of file RosePrototype.cpp.
Member Function Documentation
clone()
PlantPrototype * RosePrototype::clone () override virtual
Clone this rose prototype.
Returns
Pointer to a new RosePrototype that is a copy of this one
Implements the Prototype pattern's clone operation. Creates a new rose plant with the same characteristics as the original. Useful for propagating successful rose varieties.
Implements PlantPrototype.
Definition at line 5 of file RosePrototype.cpp.
References PlantPrototype::plant, PlantPrototype::PlantPrototype(), and RosePrototype().
The documentation for this class was generated from the following files:
Prototype - Plant Propogation/RosePrototype.h
Prototype - Plant Propogation/RosePrototype.cpp