NJD Films Greenhouse Management System: SucculentPrototype Class Reference
SucculentPrototype Class Reference
Concrete prototype implementation for succulent propagation.
#include <SucculentPrototype.h>
Public Member Functions
SucculentPrototype ()
Default constructor.
SucculentPrototype (const SucculentPrototype &other)
Copy constructor.
virtual ~SucculentPrototype ()
Virtual destructor.
PlantPrototype * clone () override
Clone this succulent prototype.
Public Member Functions inherited from PlantPrototype
PlantPrototype ()
Default constructor.
PlantPrototype (const PlantPrototype &other)
Copy constructor for cloning.
virtual ~PlantPrototype ()
Virtual destructor.
std::string getPlantType () const
Get the type/species of the plant.
int getPlantHealth () const
Get the health level of the plant.
void setPlantHealth (int h)
Set the health level of the plant.
Additional Inherited Members
Protected Attributes inherited from PlantPrototype
Plant * plant
Pointer to the plant being prototyped.
Detailed Description
Concrete prototype implementation for succulent propagation.
This class implements the Prototype pattern for succulent plants. Succulents are particularly easy to propagate through leaf or stem cuttings, making them ideal candidates for the prototype pattern. The clone() method creates new succulent plants from existing specimens, preserving their characteristics.
Definition at line 20 of file SucculentPrototype.h.
Constructor & Destructor Documentation
SucculentPrototype() [1/2]
SucculentPrototype::SucculentPrototype ()
Default constructor.
Creates a new succulent prototype with default characteristics.
Definition at line 10 of file SucculentPrototype.cpp.
References PlantPrototype::plant.
Referenced by clone(), and SucculentPrototype().
SucculentPrototype() [2/2]
SucculentPrototype::SucculentPrototype (const SucculentPrototype & other)
Copy constructor.
Parameters
other The SucculentPrototype to copy from
Creates a deep copy of another succulent prototype, used internally during the cloning process.
Definition at line 14 of file SucculentPrototype.cpp.
References PlantPrototype::PlantPrototype(), and SucculentPrototype().
~SucculentPrototype()
SucculentPrototype::~SucculentPrototype () virtual
Virtual destructor.
Definition at line 18 of file SucculentPrototype.cpp.
Member Function Documentation
clone()
PlantPrototype * SucculentPrototype::clone () override virtual
Clone this succulent prototype.
Returns
Pointer to a new SucculentPrototype that is a copy of this one
Implements the Prototype pattern's clone operation. Creates a new succulent plant with the same characteristics as the original. Succulents clone easily through leaf or stem propagation.
Implements PlantPrototype.
Definition at line 5 of file SucculentPrototype.cpp.
References PlantPrototype::plant, PlantPrototype::PlantPrototype(), and SucculentPrototype().
The documentation for this class was generated from the following files:
Prototype - Plant Propogation/SucculentPrototype.h
Prototype - Plant Propogation/SucculentPrototype.cpp