NJD Films Greenhouse Management System: PlantCareRoutine Class Reference
PlantCareRoutine Class Reference abstract
Abstract base class implementing the Template Method pattern for plant care.
#include <PlantCareRoutine.h>
Public Member Functions
virtual ~PlantCareRoutine ()=default
Virtual destructor.
void careForPlant ()
Template method defining the plant care algorithm.
Protected Member Functions
virtual void checkSoilMoisture ()=0
Pure virtual method to check soil moisture.
virtual void water ()=0
Pure virtual method to water the plant.
virtual void fertilize ()=0
Pure virtual method to fertilize the plant.
virtual void prune ()=0
Pure virtual method to prune the plant.
virtual void additionalCare ()
Hook method for additional plant-specific care.
Detailed Description
Abstract base class implementing the Template Method pattern for plant care.
This abstract class defines the skeleton of a plant care algorithm using the Template Method design pattern. It provides a fixed sequence of care steps while allowing subclasses to customize specific operations for different plant types.
The template method defines the overall care routine structure:
Check soil moisture
Water the plant
Apply fertilizer
Prune if necessary
Perform additional care (optional)
Design Pattern:
This class serves as the AbstractClass in the Template Method pattern:
AbstractClass: PlantCareRoutine (this class)
ConcreteClass: RoseCare, SucculentCare, TreeCare
Template Method: careForPlant()
Primitive Operations: checkSoilMoisture(), water(), fertilize(), prune()
Hook Operation: additionalCare()
See also
RoseCare
SucculentCare
TreeCare
Since
Version 1.0
Definition at line 43 of file PlantCareRoutine.h.
Constructor & Destructor Documentation
~PlantCareRoutine()
virtual PlantCareRoutine::~PlantCareRoutine () virtual default
Virtual destructor.
Ensures proper cleanup of derived class objects
The virtual destructor is essential for proper polymorphic destruction when deleting objects through base class pointers.
Member Function Documentation
additionalCare()
virtual void PlantCareRoutine::additionalCare () inline protected virtual
Hook method for additional plant-specific care.
Optional method that can be overridden by subclasses
This hook method provides an extension point for plant types that require additional care steps beyond the standard routine. The default implementation does nothing.
Precondition
Standard care routine steps have been completed
Postcondition
Additional care is performed if overridden
Note
Default implementation is empty (no operation) @hook This is a hook method - override is optional
Reimplemented in RoseCare, and TreeCare.
Definition at line 152 of file PlantCareRoutine.h.
Referenced by careForPlant().
careForPlant()
void PlantCareRoutine::careForPlant ()
Template method defining the plant care algorithm.
Template method implementing the plant care algorithm.
Executes the complete care routine in a fixed sequence
This is the template method that defines the skeleton of the plant care algorithm. It calls the primitive operations in a specific order to ensure consistent care across all plant types.
Algorithm Steps:
Start care routine (logging)
Check soil moisture level
Water the plant based on moisture
Apply appropriate fertilizer
Prune dead or overgrown parts
Perform additional plant-specific care
Complete care routine (logging)
Precondition
Plant care routine object must be properly constructed
Postcondition
Complete care routine is executed for the plant
Note
This method should not be overridden by subclasses @final This method defines the invariant algorithm structure
Executes the complete care routine in a predefined sequence
This method implements the Template Method pattern by defining the skeleton of the plant care algorithm. It calls primitive operations in a specific order, ensuring consistent care delivery while allowing customization through virtual method implementations in derived classes.
Algorithm Implementation:
The method follows a strict sequence:
Log routine start
Delegate soil moisture checking to subclass
Delegate watering to subclass
Delegate fertilization to subclass
Delegate pruning to subclass
Call optional additional care hook
Log routine completion
Design Pattern Benefits:
Ensures consistent care routine structure
Prevents subclasses from altering the algorithm sequence
Promotes code reuse through common algorithm skeleton
Enables customization through virtual method overrides
Maintains invariant behavior across plant types
Precondition
All pure virtual methods must be implemented by concrete subclass
Postcondition
Complete plant care routine is executed with logging
Returns
void @complexity O(1) + sum of complexities of all virtual method calls @threadsafe Depends on thread-safety of virtual method implementations
Exceptions
Depends on virtual method implementations
Note
This method should never be overridden by subclasses
Warning
Ensure all pure virtual methods are properly implemented
See also
checkSoilMoisture()
water()
fertilize()
prune()
additionalCare()
Usage Example:
RoseCare* roseCare = new RoseCare();
roseCare->careForPlant(); // Executes rose-specific care routine
Template Method Pattern:
This implementation demonstrates the Template Method pattern where:
The algorithm structure is fixed and defined here
Individual steps are customizable through virtual methods
Subclasses cannot change the overall algorithm flow
Common behavior is centralized in the base class
Definition at line 77 of file PlantCareRoutine.cpp.
References additionalCare(), checkSoilMoisture(), fertilize(), prune(), and water().
checkSoilMoisture()
virtual void PlantCareRoutine::checkSoilMoisture () protected pure virtual
Pure virtual method to check soil moisture.
Must be implemented by concrete plant care classes
Each plant type requires different moisture level checking approaches. This method allows subclasses to implement plant-specific moisture assessment techniques.
Precondition
Plant and soil conditions are accessible
Postcondition
Soil moisture level is determined
Note
Implementation varies based on plant type requirements
Warning
Must be implemented by all derived classes
Implemented in RoseCare, SucculentCare, and TreeCare.
Referenced by careForPlant().
fertilize()
virtual void PlantCareRoutine::fertilize () protected pure virtual
Pure virtual method to fertilize the plant.
Must be implemented by concrete plant care classes
Each plant type has specific nutritional requirements that determine the type and amount of fertilizer needed. This method enables plant-specific fertilization strategies.
Precondition
Plant has been watered
Postcondition
Appropriate fertilizer is applied
Note
Fertilizer type and schedule vary by plant species
Warning
Must be implemented by all derived classes
Implemented in RoseCare, SucculentCare, and TreeCare.
Referenced by careForPlant().
prune()
virtual void PlantCareRoutine::prune () protected pure virtual
Pure virtual method to prune the plant.
Must be implemented by concrete plant care classes
Pruning requirements differ significantly between plant types. This method allows implementation of species-specific pruning techniques and schedules.
Precondition
Plant has been fertilized
Postcondition
Dead or overgrown parts are removed
Note
Pruning techniques vary greatly by plant type
Warning
Must be implemented by all derived classes
Implemented in RoseCare, SucculentCare, and TreeCare.
Referenced by careForPlant().
water()
virtual void PlantCareRoutine::water () protected pure virtual
Pure virtual method to water the plant.
Must be implemented by concrete plant care classes
Different plants require different watering techniques and amounts. This method allows customization of watering approaches for specific plant types.
Precondition
Soil moisture has been checked
Postcondition
Plant receives appropriate amount of water
Note
Watering amount and frequency vary by plant type
Warning
Must be implemented by all derived classes
Implemented in RoseCare, SucculentCare, and TreeCare.
Referenced by careForPlant().
The documentation for this class was generated from the following files:
Template- Plant Care/PlantCareRoutine.h
Template- Plant Care/PlantCareRoutine.cpp