NJD Films Greenhouse Management System: GiftArrangementBuilder Class Reference
GiftArrangementBuilder Class Reference
#include <GiftArrangementBuilder.h>
Public Member Functions
GiftArrangementBuilder ()
virtual ~GiftArrangementBuilder ()
void setAvailablePlants (const std::vector< Plant * > &plants)
void reset () override
void setBasicInfo () override
void selectContainer () override
void addPlants () override
void addDecorations () override
void calculatePrice () override
Public Member Functions inherited from PlantArrangementBuilder
PlantArrangementBuilder ()
virtual ~PlantArrangementBuilder ()
PlantArrangement * getArrangement ()
Private Attributes
std::vector< Plant * > availablePlants
Additional Inherited Members
Protected Attributes inherited from PlantArrangementBuilder
PlantArrangement * arrangement
Detailed Description
Definition at line 8 of file GiftArrangementBuilder.h.
Constructor & Destructor Documentation
GiftArrangementBuilder()
GiftArrangementBuilder::GiftArrangementBuilder ()
Definition at line 6 of file GiftArrangementBuilder.cpp.
~GiftArrangementBuilder()
GiftArrangementBuilder::~GiftArrangementBuilder () virtual
Definition at line 8 of file GiftArrangementBuilder.cpp.
Member Function Documentation
addDecorations()
void GiftArrangementBuilder::addDecorations () override virtual
Implements PlantArrangementBuilder.
Definition at line 42 of file GiftArrangementBuilder.cpp.
addPlants()
void GiftArrangementBuilder::addPlants () override virtual
Implements PlantArrangementBuilder.
Definition at line 30 of file GiftArrangementBuilder.cpp.
References PlantArrangement::addPlant(), PlantArrangementBuilder::arrangement, and availablePlants.
calculatePrice()
void GiftArrangementBuilder::calculatePrice () override virtual
Implements PlantArrangementBuilder.
Definition at line 50 of file GiftArrangementBuilder.cpp.
References PlantArrangementBuilder::arrangement, and PlantArrangement::setBasePrice().
reset()
void GiftArrangementBuilder::reset () override virtual
Implements PlantArrangementBuilder.
Definition at line 14 of file GiftArrangementBuilder.cpp.
References PlantArrangementBuilder::arrangement.
selectContainer()
void GiftArrangementBuilder::selectContainer () override virtual
Implements PlantArrangementBuilder.
Definition at line 25 of file GiftArrangementBuilder.cpp.
References PlantArrangementBuilder::arrangement, and PlantArrangement::setContainerType().
setAvailablePlants()
void GiftArrangementBuilder::setAvailablePlants (const std::vector< Plant * > & plants)
Definition at line 10 of file GiftArrangementBuilder.cpp.
References availablePlants.
setBasicInfo()
void GiftArrangementBuilder::setBasicInfo () override virtual
Implements PlantArrangementBuilder.
Definition at line 19 of file GiftArrangementBuilder.cpp.
References PlantArrangementBuilder::arrangement, PlantArrangement::setDescription(), and PlantArrangement::setName().
Member Data Documentation
availablePlants
std::vector<Plant*> GiftArrangementBuilder::availablePlants private
Definition at line 10 of file GiftArrangementBuilder.h.
Referenced by addPlants(), and setAvailablePlants().
The documentation for this class was generated from the following files:
Builder - Plant Bundle Creator/GiftArrangementBuilder.h
Builder - Plant Bundle Creator/GiftArrangementBuilder.cpp