NJD Films Greenhouse Management System: PlantArrangement Class Reference
PlantArrangement Class Reference
#include <PlantArrangement.h>
Public Member Functions
PlantArrangement ()
virtual ~PlantArrangement ()
void setName (const std::string &name)
void setDescription (const std::string &desc)
void setBasePrice (double price)
void setContainerType (const std::string &container)
void addPlant (Plant *plant)
std::string getName () const
std::string getDescription () const
double getBasePrice () const
double getTotalPrice () const
std::string getContainerType () const
const std::vector< Plant * > & getPlants () const
int getPlantCount () const
void display () const
Private Attributes
std::vector< Plant * > plants
std::string name
std::string description
double basePrice
std::string containerType
Detailed Description
Definition at line 8 of file PlantArrangement.h.
Constructor & Destructor Documentation
PlantArrangement()
PlantArrangement::PlantArrangement ()
Definition at line 6 of file PlantArrangement.cpp.
~PlantArrangement()
PlantArrangement::~PlantArrangement () virtual
Definition at line 9 of file PlantArrangement.cpp.
References plants.
Member Function Documentation
addPlant()
void PlantArrangement::addPlant (Plant * plant)
Definition at line 29 of file PlantArrangement.cpp.
References plants.
Referenced by GiftArrangementBuilder::addPlants(), and LandscapeArrangementBuilder::addPlants().
display()
void PlantArrangement::display () const
Definition at line 64 of file PlantArrangement.cpp.
References basePrice, containerType, description, getTotalPrice(), name, and plants.
getBasePrice()
double PlantArrangement::getBasePrice () const
Definition at line 43 of file PlantArrangement.cpp.
References basePrice.
getContainerType()
std::string PlantArrangement::getContainerType () const
Definition at line 52 of file PlantArrangement.cpp.
References containerType.
getDescription()
std::string PlantArrangement::getDescription () const
Definition at line 39 of file PlantArrangement.cpp.
References description.
getName()
std::string PlantArrangement::getName () const
Definition at line 35 of file PlantArrangement.cpp.
References name.
getPlantCount()
int PlantArrangement::getPlantCount () const
Definition at line 60 of file PlantArrangement.cpp.
References plants.
getPlants()
const std::vector< Plant * > & PlantArrangement::getPlants () const
Definition at line 56 of file PlantArrangement.cpp.
References plants.
getTotalPrice()
double PlantArrangement::getTotalPrice () const
Definition at line 47 of file PlantArrangement.cpp.
References basePrice, and plants.
Referenced by display().
setBasePrice()
void PlantArrangement::setBasePrice (double price)
Definition at line 21 of file PlantArrangement.cpp.
References basePrice.
Referenced by GiftArrangementBuilder::calculatePrice(), and LandscapeArrangementBuilder::calculatePrice().
setContainerType()
void PlantArrangement::setContainerType (const std::string & container)
Definition at line 25 of file PlantArrangement.cpp.
References containerType.
Referenced by GiftArrangementBuilder::selectContainer(), and LandscapeArrangementBuilder::selectContainer().
setDescription()
void PlantArrangement::setDescription (const std::string & desc)
Definition at line 17 of file PlantArrangement.cpp.
References description.
Referenced by GiftArrangementBuilder::setBasicInfo(), and LandscapeArrangementBuilder::setBasicInfo().
setName()
void PlantArrangement::setName (const std::string & name)
Definition at line 13 of file PlantArrangement.cpp.
References name.
Referenced by GiftArrangementBuilder::setBasicInfo(), and LandscapeArrangementBuilder::setBasicInfo().
Member Data Documentation
basePrice
double PlantArrangement::basePrice private
Definition at line 13 of file PlantArrangement.h.
Referenced by display(), getBasePrice(), getTotalPrice(), and setBasePrice().
containerType
std::string PlantArrangement::containerType private
Definition at line 14 of file PlantArrangement.h.
Referenced by display(), getContainerType(), and setContainerType().
description
std::string PlantArrangement::description private
Definition at line 12 of file PlantArrangement.h.
Referenced by display(), getDescription(), and setDescription().
name
std::string PlantArrangement::name private
Definition at line 11 of file PlantArrangement.h.
Referenced by display(), getName(), and setName().
plants
std::vector<Plant*> PlantArrangement::plants private
Definition at line 10 of file PlantArrangement.h.
Referenced by addPlant(), display(), getPlantCount(), getPlants(), getTotalPrice(), and ~PlantArrangement().
The documentation for this class was generated from the following files:
Builder - Plant Bundle Creator/PlantArrangement.h
Builder - Plant Bundle Creator/PlantArrangement.cpp