NJD Films Greenhouse Management System: PlantProduct Class Reference
PlantProduct Class Reference abstract
Abstract component class for plant products in the Decorator pattern.
#include <PlantProduct.h>
Public Member Functions
PlantProduct ()
Default constructor.
PlantProduct (Plant *p)
Constructor with plant parameter.
virtual ~PlantProduct ()
Virtual destructor.
virtual double getPrice () const =0
Pure virtual method to get the total price.
virtual std::string getDescription () const =0
Pure virtual method to get product description.
virtual void display () const =0
Pure virtual method to display product information.
Plant * getPlant () const
Gets the underlying plant object.
void setPlant (Plant *p)
Sets the underlying plant object.
Protected Attributes
Plant * plant
Pointer to the actual plant being sold.
Detailed Description
Abstract component class for plant products in the Decorator pattern.
This class serves as the Component in the Decorator design pattern, defining the interface for objects that can have responsibilities added to them dynamically. It represents a plant product that can be sold, either as a basic plant or with various decorations added.
PlantProduct provides the base interface that both concrete components (BasicPlant) and decorators (PlantDecorator and its subclasses) must implement. This allows decorators to wrap basic plants and other decorated plants transparently.
Design Pattern Role:
Component: PlantProduct (this class)
ConcreteComponent: BasicPlant
Decorator: PlantDecorator
ConcreteDecorator: DecorativePotDecorator, GiftWrappingDecorator, GreetingCardDecorator
Usage Example:
Plant* rose = new Rose();
PlantProduct* product = new BasicPlant(rose);
product = new DecorativePotDecorator(product);
product = new GiftWrappingDecorator(product);
cout << "Price: R" << product->getPrice() << endl;
See also
BasicPlant
PlantDecorator
DecorativePotDecorator
GiftWrappingDecorator
GreetingCardDecorator
Plant
Definition at line 54 of file PlantProduct.h.
Constructor & Destructor Documentation
PlantProduct() [1/2]
PlantProduct::PlantProduct ()
Default constructor.
Initializes plant product with nullptr plant
Postcondition
plant member is set to nullptr
Definition at line 5 of file PlantProduct.cpp.
References plant.
Referenced by BasicPlant::BasicPlant(), BasicPlant::BasicPlant(), DecorativePotDecorator::DecorativePotDecorator(), PlantDecorator::getDescription(), PlantDecorator::getWrappedProduct(), GiftWrappingDecorator::GiftWrappingDecorator(), GreetingCardDecorator::GreetingCardDecorator(), PlantDecorator::PlantDecorator(), PlantDecorator::PlantDecorator(), and PlantDecorator::setWrappedProduct().
PlantProduct() [2/2]
PlantProduct::PlantProduct (Plant * p) explicit
Constructor with plant parameter.
Parameters
p Pointer to the Plant object for this product
Precondition
p should be a valid Plant pointer
Postcondition
PlantProduct is initialized with the given plant
Definition at line 7 of file PlantProduct.cpp.
References plant.
~PlantProduct()
PlantProduct::~PlantProduct () virtual
Virtual destructor.
Ensures proper cleanup of derived class objects
Note
Does not delete the plant object - ownership remains with caller
Definition at line 9 of file PlantProduct.cpp.
Member Function Documentation
display()
virtual void PlantProduct::display () const pure virtual
Pure virtual method to display product information.
Must be implemented to show product details to console
This method provides a way to output product information in a user-friendly format. Implementations should include price, description, and any relevant decorations.
Postcondition
Product information is displayed to standard output
Warning
Must be implemented by all derived classes
Implemented in BasicPlant, DecorativePotDecorator, GiftWrappingDecorator, GreetingCardDecorator, and PlantDecorator.
getDescription()
virtual std::string PlantProduct::getDescription () const pure virtual
Pure virtual method to get product description.
Returns
String description of the product including all decorations
This method must be implemented by all concrete components and decorators. Decorators typically append their description to the wrapped product's description.
Note
For decorators, this typically returns wrappedProduct->getDescription() + decoratorDesc
Warning
Must be implemented by all derived classes
Implemented in BasicPlant, DecorativePotDecorator, GiftWrappingDecorator, GreetingCardDecorator, and PlantDecorator.
getPlant()
Plant * PlantProduct::getPlant () const
Gets the underlying plant object.
Returns
Pointer to the Plant object
Provides access to the core plant that this product wraps. Useful for accessing plant-specific properties beyond the product interface.
Returns
Pointer to Plant, or nullptr if no plant is set
Note
Returned pointer should not be deleted by caller
Definition at line 13 of file PlantProduct.cpp.
References plant.
Referenced by PlantDecorator::PlantDecorator(), and PlantDecorator::setWrappedProduct().
getPrice()
virtual double PlantProduct::getPrice () const pure virtual
Pure virtual method to get the total price.
Returns
Total price of the product including all decorations
This method must be implemented by all concrete components and decorators. Decorators typically add their cost to the wrapped product's price.
Note
For decorators, this typically returns wrappedProduct->getPrice() + decoratorCost
Warning
Must be implemented by all derived classes
Implemented in BasicPlant, DecorativePotDecorator, GiftWrappingDecorator, GreetingCardDecorator, and PlantDecorator.
setPlant()
void PlantProduct::setPlant (Plant * p)
Sets the underlying plant object.
Parameters
p Pointer to the Plant object to set
Allows changing the plant associated with this product.
Precondition
p should be a valid Plant pointer
Postcondition
plant member is updated to point to p
Note
Previous plant is not deleted - caller retains ownership
Warning
Does not transfer ownership of the plant
Definition at line 17 of file PlantProduct.cpp.
References plant.
Member Data Documentation
plant
Plant* PlantProduct::plant protected
Pointer to the actual plant being sold.
Maintains reference to the Plant object that forms the core of this product
Definition at line 60 of file PlantProduct.h.
Referenced by BasicPlant::getDescription(), getPlant(), BasicPlant::getPrice(), PlantProduct(), PlantProduct(), setPlant(), and PlantDecorator::setWrappedProduct().
The documentation for this class was generated from the following files:
Decorator - Plant Decoration/PlantProduct.h
Decorator - Plant Decoration/PlantProduct.cpp