NJD Films Greenhouse Management System: PlantIterator Class Reference
PlantIterator Class Reference abstract
Abstract Iterator interface for the Iterator design pattern.
#include <PlantIterator.h>
Public Member Functions
virtual ~PlantIterator ()=default
Virtual destructor for proper cleanup of derived classes.
virtual void first ()=0
Resets the iterator to the first element.
virtual void next ()=0
Advances the iterator to the next element.
virtual bool isDone () const =0
Checks if iteration is complete.
virtual Plant * currentItem () const =0
Gets the current plant in the iteration.
Detailed Description
Abstract Iterator interface for the Iterator design pattern.
PlantIterator defines the interface for traversing a collection of Plant objects without exposing the underlying representation of the collection. This is the Iterator role in the Iterator design pattern.
The pattern provides a uniform way to access elements of different aggregate objects (like vectors, lists, or custom data structures) without needing to know the specifics of how they're stored.
Concrete implementations (like InventoryIterator) provide the actual traversal logic for specific collection types.
Note
This is an abstract interface class - cannot be instantiated directly
See also
PlantCollection, InventoryIterator, GreenhouseInventory
Example usage:
PlantCollection* inventory = new GreenhouseInventory();
PlantIterator* it = inventory->createIterator();
for (it->first(); !it->isDone(); it->next()) {
    Plant* plant = it->currentItem();
    plant->display();
}
delete it;
Definition at line 44 of file PlantIterator.h.
Constructor & Destructor Documentation
~PlantIterator()
virtual PlantIterator::~PlantIterator () virtual default
Virtual destructor for proper cleanup of derived classes.
Ensures derived iterator classes are properly destroyed when deleted through a base class pointer.
Member Function Documentation
currentItem()
virtual Plant * PlantIterator::currentItem () const pure virtual
Gets the current plant in the iteration.
Returns
Pointer to the current Plant object, or nullptr if done
Retrieves the plant at the current iterator position without advancing the iterator. Returns nullptr if iteration is complete.
Warning
Do not call when isDone() returns true
Implemented in InventoryIterator.
Referenced by InventoryManager::displayInventory().
first()
virtual void PlantIterator::first () pure virtual
Resets the iterator to the first element.
Positions the iterator at the beginning of the collection, allowing for traversal from the start. Must be called before beginning iteration.
Postcondition
Iterator points to the first element in the collection
Implemented in InventoryIterator.
Referenced by InventoryManager::displayInventory().
isDone()
virtual bool PlantIterator::isDone () const pure virtual
Checks if iteration is complete.
Returns
true if there are no more elements to iterate, false otherwise
Tests whether the iterator has passed the last element in the collection. Use this in loop conditions to determine when to stop iterating.
Implemented in InventoryIterator.
Referenced by InventoryManager::displayInventory().
next()
virtual void PlantIterator::next () pure virtual
Advances the iterator to the next element.
Moves the iterator forward to the next plant in the collection. Should be called after processing the current element.
Precondition
Iterator is not at the end of the collection
Postcondition
Iterator points to the next element, or is done if at the end
Implemented in InventoryIterator.
Referenced by InventoryManager::displayInventory().
The documentation for this class was generated from the following file:
Iterator - Inventory Management/PlantIterator.h