NJD Films Greenhouse Management System: GrowingState Class Reference
GrowingState Class Reference
Represents the active growing state in a plant's lifecycle.
#include <GrowingState.h>
Public Member Functions
virtual ~GrowingState ()=default
Virtual destructor.
void water (PlantContext *context) override
Water the growing plant regularly.
void fertilize (PlantContext *context) override
Apply moderate fertilizer for active growth.
void checkHealth (PlantContext *context) override
Check plant health and growth progress.
std::string getStateName () const override
Get the state name.
Public Member Functions inherited from PlantState
virtual ~PlantState ()=default
Virtual destructor.
Detailed Description
Represents the active growing state in a plant's lifecycle.
During the growing state, plants are actively developing and expanding. They require regular watering and moderate fertilization to support rapid growth. After reaching sufficient size, they transition to MatureState.
Definition at line 20 of file GrowingState.h.
Constructor & Destructor Documentation
~GrowingState()
virtual GrowingState::~GrowingState () virtual default
Virtual destructor.
Member Function Documentation
checkHealth()
void GrowingState::checkHealth (PlantContext * context) override virtual
Check plant health and growth progress.
Parameters
context Pointer to the PlantContext
Monitors if the plant has grown sufficiently to transition to mature state.
Implements PlantState.
Definition at line 20 of file GrowingState.cpp.
References Plant::getHealthLevel(), PlantContext::getPlant(), and PlantContext::setState().
fertilize()
void GrowingState::fertilize (PlantContext * context) override virtual
Apply moderate fertilizer for active growth.
Parameters
context Pointer to the PlantContext
Growing plants benefit from regular fertilization to support development.
Implements PlantState.
Definition at line 13 of file GrowingState.cpp.
References PlantContext::getPlant(), and Plant::modifyHealth().
getStateName()
std::string GrowingState::getStateName () const inline override virtual
Get the state name.
Returns
String "Growing"
Implements PlantState.
Definition at line 56 of file GrowingState.h.
water()
void GrowingState::water (PlantContext * context) override virtual
Water the growing plant regularly.
Parameters
context Pointer to the PlantContext
Growing plants need consistent watering to support active development. Regular watering helps transition to mature state.
Implements PlantState.
Definition at line 6 of file GrowingState.cpp.
References PlantContext::getPlant(), and Plant::modifyHealth().
The documentation for this class was generated from the following files:
State - Plant lifecycle/GrowingState.h
State - Plant lifecycle/GrowingState.cpp