NJD Films Greenhouse Management System: InventoryManager Class Reference
InventoryManager Class Reference
Facade and manager for inventory operations using the Iterator pattern.
#include <InventoryManager.h>
Public Member Functions
InventoryManager ()
Constructs an InventoryManager with no collection.
virtual ~InventoryManager ()
Virtual destructor for cleanup.
void setCollection (PlantCollection *coll)
Sets the plant collection to manage.
PlantIterator * getIterator ()
Creates an iterator for the managed collection.
void addPlant (Plant *plant)
Adds a plant to the managed collection.
void displayInventory ()
Displays all plants in the inventory using iteration.
Private Attributes
PlantCollection * collection
Pointer to the managed plant collection.
std::vector< GreenhouseComponent * > components
Vector of greenhouse components.
Detailed Description
Facade and manager for inventory operations using the Iterator pattern.
InventoryManager serves as a high-level interface for managing greenhouse inventory operations. It acts as a client of the Iterator pattern, demonstrating how to use PlantCollection and PlantIterator to manage and traverse plant data.
This class provides:
Simplified interface for inventory operations
Integration between collections and greenhouse components
Convenient methods for adding plants and displaying inventory
Iterator creation and management
The manager demonstrates the Iterator pattern's value: it can work with any PlantCollection implementation without knowing the internal storage details, relying solely on the iterator interface for traversal.
Note
This is a client class that uses the Iterator pattern
See also
PlantCollection, PlantIterator, GreenhouseInventory
Example usage:
InventoryManager* manager = new InventoryManager();
GreenhouseInventory* inventory = new GreenhouseInventory();
manager->setCollection(inventory);
manager->addPlant(new Rose());
manager->addPlant(new Cactus());
manager->displayInventory();  // Uses iterator internally
// Manual iteration
PlantIterator* it = manager->getIterator();
for (it->first(); !it->isDone(); it->next()) {
    Plant* p = it->currentItem();
    // Process plant
}
delete it;
Definition at line 58 of file InventoryManager.h.
Constructor & Destructor Documentation
InventoryManager()
InventoryManager::InventoryManager ()
Constructs an InventoryManager with no collection.
Creates a manager with collection set to nullptr. Call setCollection() before performing inventory operations.
Postcondition
collection == nullptr, components vector is empty
Definition at line 7 of file InventoryManager.cpp.
References collection.
~InventoryManager()
InventoryManager::~InventoryManager () virtual
Virtual destructor for cleanup.
Cleans up the manager. Does not delete the collection or components as they are owned by external code.
Definition at line 10 of file InventoryManager.cpp.
Member Function Documentation
addPlant()
void InventoryManager::addPlant (Plant * plant)
Adds a plant to the managed collection.
Parameters
plant Pointer to the Plant to add
Convenience method that delegates to collection->addPlant(). Does nothing if no collection is set.
Note
Does nothing if collection is nullptr
Warning
Ensure setCollection() has been called first
Definition at line 25 of file InventoryManager.cpp.
References collection.
displayInventory()
void InventoryManager::displayInventory ()
Displays all plants in the inventory using iteration.
Demonstrates the Iterator pattern by creating an iterator and traversing all plants in the collection, displaying information about each one. This method shows how to use the iterator interface without knowing the collection's internal structure.
Typical output format shows plant type, name, and other details for each plant in the inventory.
Note
Does nothing if collection is nullptr or empty
Postcondition
Inventory contents are printed to standard output
Definition at line 31 of file InventoryManager.cpp.
References collection, PlantIterator::currentItem(), PlantIterator::first(), getIterator(), PlantIterator::isDone(), and PlantIterator::next().
getIterator()
PlantIterator * InventoryManager::getIterator ()
Creates an iterator for the managed collection.
Returns
Pointer to a PlantIterator for traversing the collection
Factory method that delegates to the collection's createIterator(). Returns nullptr if no collection is set.
Note
Caller must delete the returned iterator
Returns
Iterator for the collection, or nullptr if collection is not set
Warning
Returns nullptr if setCollection() has not been called
Definition at line 18 of file InventoryManager.cpp.
References collection.
Referenced by displayInventory().
setCollection()
void InventoryManager::setCollection (PlantCollection * coll)
Sets the plant collection to manage.
Parameters
coll Pointer to a PlantCollection (typically GreenhouseInventory)
Assigns a collection for this manager to operate on. All subsequent inventory operations will use this collection.
Note
Manager does not take ownership - caller retains responsibility
Postcondition
collection points to coll
Definition at line 14 of file InventoryManager.cpp.
References collection.
Member Data Documentation
collection
PlantCollection* InventoryManager::collection private
Pointer to the managed plant collection.
Stores a reference to the PlantCollection (typically GreenhouseInventory) that this manager operates on. The manager delegates storage operations to this collection.
Note
Manager does not own the collection - caller manages its lifetime
Definition at line 69 of file InventoryManager.h.
Referenced by addPlant(), displayInventory(), getIterator(), InventoryManager(), and setCollection().
components
std::vector<GreenhouseComponent*> InventoryManager::components private
Vector of greenhouse components.
Maintains references to GreenhouseComponent objects (like Greenhouse, Section, Shelf) that may contain plants. Provides integration between the inventory system and the greenhouse layout structure.
Definition at line 78 of file InventoryManager.h.
The documentation for this class was generated from the following files:
Iterator - Inventory Management/InventoryManager.h
Iterator - Inventory Management/InventoryManager.cpp