NJD Films Greenhouse Management System: Plant Class Reference
Plant Class Reference abstract
Abstract base class representing a plant in the greenhouse system.
#include <Plant.h>
Public Member Functions
Plant ()
Default constructor.
Plant (int id, const std::string &species)
Constructor with ID and species.
virtual ~Plant ()
Virtual destructor.
Plant (const Plant &other)
Copy constructor for Prototype pattern.
virtual Plant * clone () const =0
Pure virtual clone method for Prototype pattern.
int getPlantId () const
void setPlantId (int id)
std::string getSpecies () const
void setSpecies (const std::string &species)
std::string getScientificName () const
void setScientificName (const std::string &name)
int getAge () const
void incrementAge ()
double getHeight () const
void setHeight (double h)
void grow (double amount)
double getBasePrice () const
void setBasePrice (double price)
bool isReadyForSale () const
void setReadyForSale (bool ready)
int getHealthLevel () const
void setHealthLevel (int health)
void modifyHealth (int delta)
int getWateringFrequency () const
void setWateringFrequency (int days)
int getSunlightRequirement () const
void setSunlightRequirement (int hours)
int getFertilizingFrequency () const
void setFertilizingFrequency (int days)
std::string getSoilType () const
void setSoilType (const std::string &soil)
int getDaysToMaturity () const
void setDaysToMaturity (int days)
int getCurrentGrowthDays () const
void incrementGrowthDays ()
std::string getCurrentSeason () const
void setCurrentSeason (const std::string &season)
bool isMature () const
PlantCareRoutine * getCareRoutine () const
void setCareRoutine (PlantCareRoutine *routine)
void executeCareRoutine ()
Execute the template method care routine.
PlantContext * getContext () const
void setContext (PlantContext *ctx)
PlantState * getCurrentState () const
void setState (PlantState *state)
void transitionState ()
Trigger state transition.
PlantCareStrategy * getCareStrategy () const
void setCareStrategy (PlantCareStrategy *strategy)
void applyCareStrategy ()
Apply current care strategy.
void water ()
void fertilize ()
void prune ()
void inspect ()
std::string getLastWatered () const
void updateLastWatered (const std::string &timestamp)
std::string getLastFertilized () const
void updateLastFertilized (const std::string &timestamp)
std::string getLastPruned () const
void updateLastPruned (const std::string &timestamp)
int getTimesWatered () const
int getTimesFertilized () const
int getTimesPruned () const
std::string getLocation () const
void setLocation (const std::string &loc)
int getShelfNumber () const
void setShelfNumber (int shelf)
virtual void display () const
Display plant information.
virtual std::string getType () const =0
Get plant type.
std::string getStateDescription () const
std::string getCareDescription () const
bool needsWater () const
bool needsFertilizer () const
bool needsPruning () const
bool isHealthy () const
bool needsAttention () const
void update ()
virtual void initialize ()
Initialize plant-specific values.
std::string serialize () const
void deserialize (const std::string &data)
Protected Member Functions
Plant (const std::string &species, int daysToMaturity)
Protected constructor for derived classes.
Private Attributes
int plantId
std::string species
std::string scientificName
int age
double height
double basePrice
bool readyForSale
int healthLevel
int wateringFrequency
int sunlightRequirement
int fertilizingFrequency
std::string soilType
int daysToMaturity
int currentGrowthDays
std::string currentSeason
PlantCareRoutine * careRoutine
PlantContext * context
PlantState * currentState
PlantCareStrategy * careStrategy
std::string lastWatered
std::string lastFertilized
std::string lastPruned
int timesWatered
int timesFertilized
int timesPruned
std::string location
int shelfNumber
Detailed Description
Abstract base class representing a plant in the greenhouse system.
Plant serves as the abstract base for all plant types in the greenhouse management system. It maintains comprehensive plant data including identity, physical characteristics, care requirements, lifecycle state, and pattern-based behaviors.
The class integrates multiple design patterns:
Prototype: Supports cloning via pure virtual clone() method
Template: Uses PlantCareRoutine for standardized care procedures
State: Manages lifecycle stages (seedling, growing, mature, flowering, dormant)
Strategy: Applies different care strategies (frequent, moderate, minimal watering)
Key Responsibilities:
Track plant identity, species, age, and health
Manage growth and maturity lifecycle
Store care requirements (watering, sunlight, fertilizing, soil)
Maintain care history (last watered, fertilized, pruned)
Support pattern-based behaviors (clone, state transitions, care strategies)
Design Pattern Roles:
Prototype: Abstract prototype defining clone() interface
Template: Client of PlantCareRoutine template method
State: Context maintaining current PlantState
Strategy: Context using PlantCareStrategy
See also
PlantCareRoutine
PlantContext
PlantState
PlantCareStrategy
Definition at line 53 of file Plant.h.
Constructor & Destructor Documentation
Plant() [1/4]
Plant::Plant (const std::string & species, int daysToMaturity) protected
Protected constructor for derived classes.
Parameters
species Species name
daysToMaturity Days until plant reaches maturity
Definition at line 28 of file Plant.cpp.
References daysToMaturity, Plant(), and species.
Referenced by Baobab::Baobab(), Baobab::Baobab(), Cactus::Cactus(), Cactus::Cactus(), Baobab::clone(), Cactus::clone(), Lavender::clone(), clone(), Rose::clone(), Succulent::clone(), Lavender::Lavender(), Lavender::Lavender(), Plant(), Plant(), Plant(), Rose::Rose(), Rose::Rose(), Succulent::Succulent(), and Succulent::Succulent().
Plant() [2/4]
Plant::Plant ()
Default constructor.
Definition at line 13 of file Plant.cpp.
References age, basePrice, careRoutine, careStrategy, context, currentGrowthDays, currentSeason, currentState, daysToMaturity, fertilizingFrequency, healthLevel, height, plantId, readyForSale, scientificName, shelfNumber, soilType, species, sunlightRequirement, timesFertilized, timesPruned, timesWatered, and wateringFrequency.
Plant() [3/4]
Plant::Plant (int id, const std::string & species)
Constructor with ID and species.
Parameters
id Plant ID
species Species name
Definition at line 22 of file Plant.cpp.
References Plant(), plantId, and species.
~Plant()
Plant::~Plant () virtual
Virtual destructor.
Definition at line 34 of file Plant.cpp.
Plant() [4/4]
Plant::Plant (const Plant & other)
Copy constructor for Prototype pattern.
Parameters
other Plant to copy from
Definition at line 39 of file Plant.cpp.
References age, basePrice, careRoutine, careStrategy, context, currentGrowthDays, currentSeason, currentState, daysToMaturity, fertilizingFrequency, healthLevel, height, location, Plant(), plantId, readyForSale, scientificName, shelfNumber, soilType, species, sunlightRequirement, timesFertilized, timesPruned, timesWatered, and wateringFrequency.
Member Function Documentation
applyCareStrategy()
void Plant::applyCareStrategy ()
Apply current care strategy.
Note
Uses Strategy Pattern for watering approach
Definition at line 149 of file Plant.cpp.
References careStrategy.
clone()
virtual Plant * Plant::clone () const pure virtual
Pure virtual clone method for Prototype pattern.
Returns
Pointer to cloned plant
Note
Must be implemented by derived classes
Implemented in Baobab, Baobab, Cactus, Cactus, Lavender, Lavender, Rose, Rose, Succulent, and Succulent.
References Plant(), and species.
Referenced by PlantPrototype::PlantPrototype().
deserialize()
void Plant::deserialize (const std::string & data)
Definition at line 293 of file Plant.cpp.
display()
void Plant::display () const virtual
Display plant information.
Note
Virtual for polymorphic behavior
Reimplemented in Baobab, Cactus, Lavender, Rose, and Succulent.
Definition at line 215 of file Plant.cpp.
References age, basePrice, currentGrowthDays, daysToMaturity, getType(), healthLevel, height, location, plantId, readyForSale, and species.
Referenced by Baobab::display(), Cactus::display(), Lavender::display(), Rose::display(), Succulent::display(), and inspect().
executeCareRoutine()
void Plant::executeCareRoutine ()
Execute the template method care routine.
Note
Uses Template Pattern through PlantCareRoutine
Definition at line 128 of file Plant.cpp.
References careRoutine.
fertilize()
void Plant::fertilize ()
Definition at line 167 of file Plant.cpp.
References grow(), healthLevel, height, lastFertilized, modifyHealth(), plantId, species, and timesFertilized.
getAge()
int Plant::getAge () const
Definition at line 66 of file Plant.cpp.
References age.
getBasePrice()
double Plant::getBasePrice () const
Definition at line 75 of file Plant.cpp.
References basePrice.
getCareDescription()
std::string Plant::getCareDescription () const
Definition at line 236 of file Plant.cpp.
References fertilizingFrequency, and wateringFrequency.
getCareRoutine()
PlantCareRoutine * Plant::getCareRoutine () const
Definition at line 126 of file Plant.cpp.
References careRoutine.
getCareStrategy()
PlantCareStrategy * Plant::getCareStrategy () const
Definition at line 147 of file Plant.cpp.
References careStrategy.
getContext()
PlantContext * Plant::getContext () const
Definition at line 135 of file Plant.cpp.
References context.
getCurrentGrowthDays()
int Plant::getCurrentGrowthDays () const
Definition at line 110 of file Plant.cpp.
References currentGrowthDays.
getCurrentSeason()
std::string Plant::getCurrentSeason () const
Definition at line 119 of file Plant.cpp.
References currentSeason.
getCurrentState()
PlantState * Plant::getCurrentState () const
Definition at line 138 of file Plant.cpp.
References currentState.
getDaysToMaturity()
int Plant::getDaysToMaturity () const
Definition at line 107 of file Plant.cpp.
References daysToMaturity.
getFertilizingFrequency()
int Plant::getFertilizingFrequency () const
Definition at line 99 of file Plant.cpp.
References fertilizingFrequency.
getHealthLevel()
int Plant::getHealthLevel () const
Definition at line 81 of file Plant.cpp.
References healthLevel.
Referenced by GrowingState::checkHealth(), and SeedlingState::checkHealth().
getHeight()
double Plant::getHeight () const
Definition at line 71 of file Plant.cpp.
References height.
getLastFertilized()
std::string Plant::getLastFertilized () const
Definition at line 195 of file Plant.cpp.
References lastFertilized.
getLastPruned()
std::string Plant::getLastPruned () const
Definition at line 198 of file Plant.cpp.
References lastPruned.
getLastWatered()
std::string Plant::getLastWatered () const
Definition at line 192 of file Plant.cpp.
References lastWatered.
getLocation()
std::string Plant::getLocation () const
Definition at line 207 of file Plant.cpp.
References location.
getPlantId()
int Plant::getPlantId () const
Definition at line 57 of file Plant.cpp.
References plantId.
getScientificName()
std::string Plant::getScientificName () const
Definition at line 63 of file Plant.cpp.
References scientificName.
Referenced by Baobab::display(), Cactus::display(), Lavender::display(), Rose::display(), and Succulent::display().
getShelfNumber()
int Plant::getShelfNumber () const
Definition at line 210 of file Plant.cpp.
References shelfNumber.
getSoilType()
std::string Plant::getSoilType () const
Definition at line 102 of file Plant.cpp.
References soilType.
getSpecies()
std::string Plant::getSpecies () const
Definition at line 60 of file Plant.cpp.
References species.
getStateDescription()
std::string Plant::getStateDescription () const
Definition at line 228 of file Plant.cpp.
References currentState.
getSunlightRequirement()
int Plant::getSunlightRequirement () const
Definition at line 96 of file Plant.cpp.
References sunlightRequirement.
getTimesFertilized()
int Plant::getTimesFertilized () const
Definition at line 202 of file Plant.cpp.
References timesFertilized.
getTimesPruned()
int Plant::getTimesPruned () const
Definition at line 203 of file Plant.cpp.
References timesPruned.
getTimesWatered()
int Plant::getTimesWatered () const
Definition at line 201 of file Plant.cpp.
References timesWatered.
getType()
virtual std::string Plant::getType () const pure virtual
Get plant type.
Returns
Type string (e.g., "Rose", "Cactus")
Note
Pure virtual - must be implemented by derived classes
Implemented in Baobab, Baobab, Cactus, Cactus, Lavender, Lavender, Rose, Rose, Succulent, and Succulent.
Referenced by display().
getWateringFrequency()
int Plant::getWateringFrequency () const
Definition at line 93 of file Plant.cpp.
References wateringFrequency.
grow()
void Plant::grow (double amount)
Definition at line 73 of file Plant.cpp.
References height.
Referenced by fertilize(), and update().
incrementAge()
void Plant::incrementAge ()
Definition at line 67 of file Plant.cpp.
References age.
Referenced by update().
incrementGrowthDays()
void Plant::incrementGrowthDays ()
Definition at line 111 of file Plant.cpp.
References currentGrowthDays, daysToMaturity, plantId, readyForSale, and species.
Referenced by update().
initialize()
void Plant::initialize () virtual
Initialize plant-specific values.
Note
Virtual for derived class customization
Reimplemented in Baobab, Cactus, Lavender, Rose, and Succulent.
Definition at line 280 of file Plant.cpp.
inspect()
void Plant::inspect ()
Definition at line 185 of file Plant.cpp.
References display().
isHealthy()
bool Plant::isHealthy () const
Definition at line 258 of file Plant.cpp.
References healthLevel.
Referenced by needsAttention(), and update().
isMature()
bool Plant::isMature () const
Definition at line 122 of file Plant.cpp.
References currentGrowthDays, and daysToMaturity.
isReadyForSale()
bool Plant::isReadyForSale () const
Definition at line 78 of file Plant.cpp.
References readyForSale.
modifyHealth()
void Plant::modifyHealth (int delta)
Definition at line 87 of file Plant.cpp.
References healthLevel, and setHealthLevel().
Referenced by FloweringState::fertilize(), GrowingState::fertilize(), MatureState::fertilize(), fertilize(), SeedlingState::fertilize(), prune(), update(), DormantState::water(), FloweringState::water(), GrowingState::water(), MatureState::water(), water(), and SeedlingState::water().
needsAttention()
bool Plant::needsAttention () const
Definition at line 262 of file Plant.cpp.
References isHealthy(), needsFertilizer(), needsPruning(), and needsWater().
needsFertilizer()
bool Plant::needsFertilizer () const
Definition at line 250 of file Plant.cpp.
References age, fertilizingFrequency, and timesFertilized.
Referenced by needsAttention(), and update().
needsPruning()
bool Plant::needsPruning () const
Definition at line 254 of file Plant.cpp.
References height, and timesPruned.
Referenced by needsAttention().
needsWater()
bool Plant::needsWater () const
Definition at line 245 of file Plant.cpp.
References age, timesWatered, and wateringFrequency.
Referenced by needsAttention(), and update().
prune()
void Plant::prune ()
Definition at line 177 of file Plant.cpp.
References lastPruned, modifyHealth(), plantId, species, and timesPruned.
serialize()
std::string Plant::serialize () const
Definition at line 286 of file Plant.cpp.
References age, healthLevel, height, plantId, readyForSale, and species.
setBasePrice()
void Plant::setBasePrice (double price)
Definition at line 76 of file Plant.cpp.
References basePrice.
Referenced by Baobab::Baobab(), Cactus::Cactus(), Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), Succulent::initialize(), Lavender::Lavender(), Rose::Rose(), and Succulent::Succulent().
setCareRoutine()
void Plant::setCareRoutine (PlantCareRoutine * routine)
Definition at line 127 of file Plant.cpp.
References careRoutine.
setCareStrategy()
void Plant::setCareStrategy (PlantCareStrategy * strategy)
Definition at line 148 of file Plant.cpp.
References careStrategy.
setContext()
void Plant::setContext (PlantContext * ctx)
Definition at line 136 of file Plant.cpp.
References context.
setCurrentSeason()
void Plant::setCurrentSeason (const std::string & season)
Definition at line 120 of file Plant.cpp.
References currentSeason.
Referenced by Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), and Succulent::initialize().
setDaysToMaturity()
void Plant::setDaysToMaturity (int days)
Definition at line 108 of file Plant.cpp.
References daysToMaturity.
setFertilizingFrequency()
void Plant::setFertilizingFrequency (int days)
Definition at line 100 of file Plant.cpp.
References fertilizingFrequency.
Referenced by Baobab::Baobab(), Cactus::Cactus(), Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), Succulent::initialize(), Lavender::Lavender(), and Succulent::Succulent().
setHealthLevel()
void Plant::setHealthLevel (int health)
Definition at line 82 of file Plant.cpp.
References healthLevel.
Referenced by Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), Succulent::initialize(), and modifyHealth().
setHeight()
void Plant::setHeight (double h)
Definition at line 72 of file Plant.cpp.
References height.
Referenced by Baobab::Baobab(), Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), and Succulent::initialize().
setLocation()
void Plant::setLocation (const std::string & loc)
Definition at line 208 of file Plant.cpp.
References location.
setPlantId()
void Plant::setPlantId (int id)
Definition at line 58 of file Plant.cpp.
References plantId.
setReadyForSale()
void Plant::setReadyForSale (bool ready)
Definition at line 79 of file Plant.cpp.
References readyForSale.
setScientificName()
void Plant::setScientificName (const std::string & name)
Definition at line 64 of file Plant.cpp.
References scientificName.
Referenced by Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), and Succulent::initialize().
setShelfNumber()
void Plant::setShelfNumber (int shelf)
Definition at line 211 of file Plant.cpp.
References shelfNumber.
setSoilType()
void Plant::setSoilType (const std::string & soil)
Definition at line 103 of file Plant.cpp.
References soilType.
Referenced by Baobab::Baobab(), Cactus::Cactus(), Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), Succulent::initialize(), Lavender::Lavender(), Rose::Rose(), and Succulent::Succulent().
setSpecies()
void Plant::setSpecies (const std::string & species)
Definition at line 61 of file Plant.cpp.
References species.
setState()
void Plant::setState (PlantState * state)
Definition at line 139 of file Plant.cpp.
References currentState.
setSunlightRequirement()
void Plant::setSunlightRequirement (int hours)
Definition at line 97 of file Plant.cpp.
References sunlightRequirement.
Referenced by Baobab::Baobab(), Cactus::Cactus(), Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), Succulent::initialize(), Lavender::Lavender(), and Succulent::Succulent().
setWateringFrequency()
void Plant::setWateringFrequency (int days)
Definition at line 94 of file Plant.cpp.
References wateringFrequency.
Referenced by Baobab::Baobab(), Cactus::Cactus(), Baobab::initialize(), Cactus::initialize(), Lavender::initialize(), Rose::initialize(), Succulent::initialize(), Lavender::Lavender(), Rose::Rose(), and Succulent::Succulent().
transitionState()
void Plant::transitionState ()
Trigger state transition.
Note
Uses State Pattern to move between lifecycle stages
Definition at line 140 of file Plant.cpp.
References context.
update()
void Plant::update ()
Definition at line 268 of file Plant.cpp.
References grow(), incrementAge(), incrementGrowthDays(), isHealthy(), modifyHealth(), needsFertilizer(), and needsWater().
updateLastFertilized()
void Plant::updateLastFertilized (const std::string & timestamp)
Definition at line 196 of file Plant.cpp.
References lastFertilized.
updateLastPruned()
void Plant::updateLastPruned (const std::string & timestamp)
Definition at line 199 of file Plant.cpp.
References lastPruned.
updateLastWatered()
void Plant::updateLastWatered (const std::string & timestamp)
Definition at line 193 of file Plant.cpp.
References lastWatered.
water()
void Plant::water ()
Definition at line 158 of file Plant.cpp.
References healthLevel, lastWatered, modifyHealth(), plantId, species, and timesWatered.
Member Data Documentation
age
int Plant::age private
Definition at line 59 of file Plant.h.
Referenced by display(), getAge(), incrementAge(), needsFertilizer(), needsWater(), Plant(), Plant(), and serialize().
basePrice
double Plant::basePrice private
Definition at line 63 of file Plant.h.
Referenced by display(), getBasePrice(), Plant(), Plant(), and setBasePrice().
careRoutine
PlantCareRoutine* Plant::careRoutine private
Definition at line 79 of file Plant.h.
Referenced by executeCareRoutine(), getCareRoutine(), Plant(), Plant(), and setCareRoutine().
careStrategy
PlantCareStrategy* Plant::careStrategy private
Definition at line 82 of file Plant.h.
Referenced by applyCareStrategy(), getCareStrategy(), Plant(), Plant(), and setCareStrategy().
context
PlantContext* Plant::context private
Definition at line 80 of file Plant.h.
Referenced by getContext(), Plant(), Plant(), setContext(), and transitionState().
currentGrowthDays
int Plant::currentGrowthDays private
Definition at line 75 of file Plant.h.
Referenced by display(), getCurrentGrowthDays(), incrementGrowthDays(), isMature(), Plant(), and Plant().
currentSeason
std::string Plant::currentSeason private
Definition at line 76 of file Plant.h.
Referenced by getCurrentSeason(), Plant(), Plant(), and setCurrentSeason().
currentState
PlantState* Plant::currentState private
Definition at line 81 of file Plant.h.
Referenced by getCurrentState(), getStateDescription(), Plant(), Plant(), and setState().
daysToMaturity
int Plant::daysToMaturity private
Definition at line 74 of file Plant.h.
Referenced by display(), getDaysToMaturity(), incrementGrowthDays(), isMature(), Plant(), Plant(), Plant(), and setDaysToMaturity().
fertilizingFrequency
int Plant::fertilizingFrequency private
Definition at line 70 of file Plant.h.
Referenced by getCareDescription(), getFertilizingFrequency(), needsFertilizer(), Plant(), Plant(), and setFertilizingFrequency().
healthLevel
int Plant::healthLevel private
Definition at line 65 of file Plant.h.
Referenced by display(), fertilize(), getHealthLevel(), isHealthy(), modifyHealth(), Plant(), Plant(), serialize(), setHealthLevel(), and water().
height
double Plant::height private
Definition at line 62 of file Plant.h.
Referenced by display(), fertilize(), getHeight(), grow(), needsPruning(), Plant(), Plant(), serialize(), and setHeight().
lastFertilized
std::string Plant::lastFertilized private
Definition at line 86 of file Plant.h.
Referenced by fertilize(), getLastFertilized(), and updateLastFertilized().
lastPruned
std::string Plant::lastPruned private
Definition at line 87 of file Plant.h.
Referenced by getLastPruned(), prune(), and updateLastPruned().
lastWatered
std::string Plant::lastWatered private
Definition at line 85 of file Plant.h.
Referenced by getLastWatered(), updateLastWatered(), and water().
location
std::string Plant::location private
Definition at line 93 of file Plant.h.
Referenced by display(), getLocation(), Plant(), and setLocation().
plantId
int Plant::plantId private
Definition at line 56 of file Plant.h.
Referenced by display(), fertilize(), getPlantId(), incrementGrowthDays(), Plant(), Plant(), Plant(), prune(), serialize(), setPlantId(), and water().
readyForSale
bool Plant::readyForSale private
Definition at line 64 of file Plant.h.
Referenced by display(), incrementGrowthDays(), isReadyForSale(), Plant(), Plant(), serialize(), and setReadyForSale().
scientificName
std::string Plant::scientificName private
Definition at line 58 of file Plant.h.
Referenced by getScientificName(), Plant(), Plant(), and setScientificName().
shelfNumber
int Plant::shelfNumber private
Definition at line 94 of file Plant.h.
Referenced by getShelfNumber(), Plant(), Plant(), and setShelfNumber().
soilType
std::string Plant::soilType private
Definition at line 71 of file Plant.h.
Referenced by getSoilType(), Plant(), Plant(), and setSoilType().
species
std::string Plant::species private
Definition at line 57 of file Plant.h.
Referenced by clone(), display(), fertilize(), getSpecies(), incrementGrowthDays(), Plant(), Plant(), Plant(), Plant(), prune(), serialize(), setSpecies(), and water().
sunlightRequirement
int Plant::sunlightRequirement private
Definition at line 69 of file Plant.h.
Referenced by getSunlightRequirement(), Plant(), Plant(), and setSunlightRequirement().
timesFertilized
int Plant::timesFertilized private
Definition at line 89 of file Plant.h.
Referenced by fertilize(), getTimesFertilized(), needsFertilizer(), Plant(), and Plant().
timesPruned
int Plant::timesPruned private
Definition at line 90 of file Plant.h.
Referenced by getTimesPruned(), needsPruning(), Plant(), Plant(), and prune().
timesWatered
int Plant::timesWatered private
Definition at line 88 of file Plant.h.
Referenced by getTimesWatered(), needsWater(), Plant(), Plant(), and water().
wateringFrequency
int Plant::wateringFrequency private
Definition at line 68 of file Plant.h.
Referenced by getCareDescription(), getWateringFrequency(), needsWater(), Plant(), Plant(), and setWateringFrequency().
The documentation for this class was generated from the following files:
Plant - Abstract Base/Plant.h
Plant - Abstract Base/Plant.cpp