NJD Films Greenhouse Management System: PlantPrototype Class Reference
PlantPrototype Class Reference abstract
Abstract prototype class for cloning plants.
#include <PlantPrototype.h>
Public Member Functions
PlantPrototype ()
Default constructor.
PlantPrototype (const PlantPrototype &other)
Copy constructor for cloning.
virtual ~PlantPrototype ()
Virtual destructor.
virtual PlantPrototype * clone ()=0
Clone this prototype (pure virtual)
std::string getPlantType () const
Get the type/species of the plant.
int getPlantHealth () const
Get the health level of the plant.
void setPlantHealth (int h)
Set the health level of the plant.
Protected Attributes
Plant * plant
Pointer to the plant being prototyped.
Detailed Description
Abstract prototype class for cloning plants.
This class implements the Prototype design pattern, allowing plants to be cloned/propagated without knowing their concrete types. This is useful for creating new plants from existing specimens through vegetative propagation (cuttings, division, etc.). Each concrete prototype knows how to clone itself.
Definition at line 23 of file PlantPrototype.h.
Constructor & Destructor Documentation
PlantPrototype() [1/2]
PlantPrototype::PlantPrototype ()
Default constructor.
Definition at line 4 of file PlantPrototype.cpp.
References plant.
Referenced by clone(), RosePrototype::clone(), SucculentPrototype::clone(), PlantPrototype(), RosePrototype::RosePrototype(), and SucculentPrototype::SucculentPrototype().
PlantPrototype() [2/2]
PlantPrototype::PlantPrototype (const PlantPrototype & other)
Copy constructor for cloning.
Parameters
other The PlantPrototype to copy from
Creates a deep copy of the prototype including its plant data.
Definition at line 6 of file PlantPrototype.cpp.
References Plant::clone(), plant, and PlantPrototype().
~PlantPrototype()
PlantPrototype::~PlantPrototype () virtual
Virtual destructor.
Definition at line 17 of file PlantPrototype.cpp.
References plant.
Member Function Documentation
clone()
virtual PlantPrototype * PlantPrototype::clone () pure virtual
Clone this prototype (pure virtual)
Returns
Pointer to a new PlantPrototype that is a copy of this one
Concrete subclasses must implement this to create clones of themselves. This is the key method of the Prototype pattern.
Implemented in RosePrototype, and SucculentPrototype.
References PlantPrototype().
getPlantHealth()
int PlantPrototype::getPlantHealth () const
Get the health level of the plant.
Returns
Integer representing plant health (typically 0-100)
Definition at line 27 of file PlantPrototype.cpp.
References plant.
getPlantType()
std::string PlantPrototype::getPlantType () const
Get the type/species of the plant.
Returns
String containing the plant type
Definition at line 23 of file PlantPrototype.cpp.
References plant.
setPlantHealth()
void PlantPrototype::setPlantHealth (int h)
Set the health level of the plant.
Parameters
h New health value to set
Definition at line 31 of file PlantPrototype.cpp.
References plant.
Member Data Documentation
plant
Plant* PlantPrototype::plant protected
Pointer to the plant being prototyped.
Definition at line 25 of file PlantPrototype.h.
Referenced by RosePrototype::clone(), SucculentPrototype::clone(), getPlantHealth(), getPlantType(), PlantPrototype(), PlantPrototype(), RosePrototype::RosePrototype(), setPlantHealth(), SucculentPrototype::SucculentPrototype(), and ~PlantPrototype().
The documentation for this class was generated from the following files:
Prototype - Plant Propogation/PlantPrototype.h
Prototype - Plant Propogation/PlantPrototype.cpp