NJD Films Greenhouse Management System: PlantLeaf Class Reference
PlantLeaf Class Reference
Leaf node in the Composite pattern representing an individual plant.
#include <PlantLeaf.h>
Public Member Functions
PlantLeaf (Plant *p, const std::string &name="Plant")
Constructs a PlantLeaf wrapping a Plant object.
virtual ~PlantLeaf ()
Virtual destructor for proper cleanup.
void display (int depth=0) const override
Displays this plant's information.
Plant * getPlant () const
Gets the wrapped Plant object.
void add (GreenhouseComponent *component) override
No-op operation for leaf nodes - cannot add children.
void remove (GreenhouseComponent *component) override
No-op operation for leaf nodes - cannot remove children.
GreenhouseComponent * getChild (int index) const override
Always returns nullptr for leaf nodes.
bool isComposite () const override
Indicates that PlantLeaf is a leaf node.
Public Member Functions inherited from GreenhouseComponent
GreenhouseComponent (const std::string &componentName="")
Constructs a GreenhouseComponent with an optional name.
virtual ~GreenhouseComponent ()
Virtual destructor to ensure proper cleanup of derived classes.
virtual int getChildCount () const
Gets the number of children this component has.
std::string getName () const
Gets the name of this component.
Private Attributes
Plant * plant
Pointer to the actual Plant object this leaf represents.
Additional Inherited Members
Protected Attributes inherited from GreenhouseComponent
std::vector< GreenhouseComponent * > children
Container for child components in the composite structure.
std::string name
Name identifier for this component.
Detailed Description
Leaf node in the Composite pattern representing an individual plant.
PlantLeaf is the leaf class in the Composite pattern hierarchy. It represents individual plant objects that cannot have children. Unlike composite nodes (Greenhouse, GreenhouseSection, Shelf), a PlantLeaf wraps a single Plant object and provides no-op implementations for child management operations.
This class demonstrates the key principle of the Composite pattern: treating leaf and composite objects uniformly through the same interface, even though leaf nodes don't support child operations.
Note
This is a Leaf node - it cannot have children
See also
GreenhouseComponent, Plant, Shelf
Example usage:
Plant* rose = new Rose();
PlantLeaf* leaf = new PlantLeaf(rose, "Beautiful Red Rose");
shelf->add(leaf);  // Add to shelf
leaf->display();   // Display plant info
Definition at line 39 of file PlantLeaf.h.
Constructor & Destructor Documentation
PlantLeaf()
PlantLeaf::PlantLeaf (Plant * p, const std::string & name = "Plant")
Constructs a PlantLeaf wrapping a Plant object.
Parameters
p Pointer to the Plant object to wrap
name Display name for this plant leaf (default: "Plant")
Creates a leaf node that represents an individual plant in the greenhouse hierarchy. The Plant pointer must remain valid for the lifetime of this PlantLeaf.
Warning
The caller is responsible for the lifetime of the Plant object
Definition at line 6 of file PlantLeaf.cpp.
References GreenhouseComponent::GreenhouseComponent(), GreenhouseComponent::name, and plant.
~PlantLeaf()
PlantLeaf::~PlantLeaf () virtual
Virtual destructor for proper cleanup.
Cleans up the PlantLeaf. Note that this does not delete the wrapped Plant object - the caller maintains ownership of the Plant.
Definition at line 10 of file PlantLeaf.cpp.
References plant.
Member Function Documentation
add()
void PlantLeaf::add (GreenhouseComponent * component) override virtual
No-op operation for leaf nodes - cannot add children.
Parameters
component Component to add (ignored)
Since PlantLeaf is a leaf node, it cannot have children. This method is a no-op (does nothing) to maintain interface consistency.
Note
This operation does nothing for leaf nodes
Reimplemented from GreenhouseComponent.
Definition at line 24 of file PlantLeaf.cpp.
References GreenhouseComponent::GreenhouseComponent().
display()
void PlantLeaf::display (int depth = 0) const override virtual
Displays this plant's information.
Parameters
depth The indentation depth for hierarchical display (default: 0)
Displays the plant's information with appropriate indentation to show its position in the greenhouse hierarchy. Shows plant-specific details such as type, state, and other properties.
Implements GreenhouseComponent.
Definition at line 15 of file PlantLeaf.cpp.
References GreenhouseComponent::getName().
getChild()
GreenhouseComponent * PlantLeaf::getChild (int index) const override virtual
Always returns nullptr for leaf nodes.
Parameters
index Child index (ignored)
Returns
Always returns nullptr as leaf nodes have no children
Leaf nodes cannot have children, so this always returns nullptr regardless of the index provided.
Reimplemented from GreenhouseComponent.
Definition at line 34 of file PlantLeaf.cpp.
References GreenhouseComponent::GreenhouseComponent().
getPlant()
Plant * PlantLeaf::getPlant () const
Gets the wrapped Plant object.
Returns
Pointer to the Plant object this leaf represents
Definition at line 20 of file PlantLeaf.cpp.
References plant.
isComposite()
bool PlantLeaf::isComposite () const override virtual
Indicates that PlantLeaf is a leaf node.
Returns
Always returns false as PlantLeaf cannot contain children
Reimplemented from GreenhouseComponent.
Definition at line 39 of file PlantLeaf.cpp.
remove()
void PlantLeaf::remove (GreenhouseComponent * component) override virtual
No-op operation for leaf nodes - cannot remove children.
Parameters
component Component to remove (ignored)
Since PlantLeaf is a leaf node, it cannot have children. This method is a no-op (does nothing) to maintain interface consistency.
Note
This operation does nothing for leaf nodes
Reimplemented from GreenhouseComponent.
Definition at line 29 of file PlantLeaf.cpp.
References GreenhouseComponent::GreenhouseComponent().
Member Data Documentation
plant
Plant* PlantLeaf::plant private
Pointer to the actual Plant object this leaf represents.
Stores the Plant that this leaf node wraps. The PlantLeaf acts as an adapter between the Plant class and the Composite pattern hierarchy.
Definition at line 47 of file PlantLeaf.h.
Referenced by getPlant(), PlantLeaf(), and ~PlantLeaf().
The documentation for this class was generated from the following files:
Composite - The Store layout/PlantLeaf.h
Composite - The Store layout/PlantLeaf.cpp