NJD Films Greenhouse Management System: GreenhouseComponent Class Reference
GreenhouseComponent Class Reference abstract
Abstract Component class in the Composite pattern for greenhouse store layout.
#include <GreenhouseComponent.h>
Public Member Functions
GreenhouseComponent (const std::string &componentName="")
Constructs a GreenhouseComponent with an optional name.
virtual ~GreenhouseComponent ()
Virtual destructor to ensure proper cleanup of derived classes.
virtual void display (int depth=0) const =0
Pure virtual method to display component information.
virtual void add (GreenhouseComponent *component)
Adds a child component to this component.
virtual void remove (GreenhouseComponent *component)
Removes a child component from this component.
virtual GreenhouseComponent * getChild (int index) const
Retrieves a child component at the specified index.
virtual int getChildCount () const
Gets the number of children this component has.
std::string getName () const
Gets the name of this component.
virtual bool isComposite () const
Checks if this component is a composite (has children)
Protected Attributes
std::vector< GreenhouseComponent * > children
Container for child components in the composite structure.
std::string name
Name identifier for this component.
Detailed Description
Abstract Component class in the Composite pattern for greenhouse store layout.
This class serves as the base component in a Composite design pattern implementation for managing hierarchical greenhouse store structures. It defines the common interface for both leaf objects (PlantLeaf) and composite objects (Greenhouse, GreenhouseSection, Shelf).
The pattern allows clients to treat individual plants and groups of plants uniformly, enabling operations on entire greenhouse structures or individual components.
Note
This is an abstract class and cannot be instantiated directly
See also
Greenhouse, GreenhouseSection, Shelf, PlantLeaf
Definition at line 33 of file GreenhouseComponent.h.
Constructor & Destructor Documentation
GreenhouseComponent()
GreenhouseComponent::GreenhouseComponent (const std::string & componentName = "")
Constructs a GreenhouseComponent with an optional name.
Parameters
componentName The name for this component (default: empty string)
Definition at line 4 of file GreenhouseComponent.cpp.
References name.
Referenced by add(), PlantLeaf::add(), display(), getChild(), PlantLeaf::getChild(), Greenhouse::Greenhouse(), GreenhouseSection::GreenhouseSection(), PlantLeaf::PlantLeaf(), remove(), PlantLeaf::remove(), and Shelf::Shelf().
~GreenhouseComponent()
GreenhouseComponent::~GreenhouseComponent () virtual
Virtual destructor to ensure proper cleanup of derived classes.
Ensures that derived class destructors are called when deleting through a base class pointer, preventing memory leaks
Definition at line 8 of file GreenhouseComponent.cpp.
References children.
Member Function Documentation
add()
void GreenhouseComponent::add (GreenhouseComponent * component) virtual
Adds a child component to this component.
Parameters
component Pointer to the GreenhouseComponent to add as a child
For leaf nodes, this operation may do nothing or throw an exception. For composite nodes, it adds the component to the children vector.
Note
The caller is responsible for ensuring the component pointer remains valid
Warning
Adding null pointers or already-added components may cause undefined behavior
Reimplemented in PlantLeaf.
Definition at line 16 of file GreenhouseComponent.cpp.
References children, and GreenhouseComponent().
display()
virtual void GreenhouseComponent::display (int depth = 0) const pure virtual
Pure virtual method to display component information.
Parameters
depth Indentation depth for hierarchical display (default: 0)
This method must be implemented by all concrete classes. It displays the component's information with proper indentation to show hierarchy.
Implemented in Greenhouse, GreenhouseSection, PlantLeaf, and Shelf.
References GreenhouseComponent().
getChild()
GreenhouseComponent * GreenhouseComponent::getChild (int index) const virtual
Retrieves a child component at the specified index.
Parameters
index Zero-based index of the child to retrieve
Returns
Pointer to the child component, or nullptr if index is invalid
Warning
Accessing an out-of-bounds index may return nullptr or cause undefined behavior
Reimplemented in PlantLeaf.
Definition at line 29 of file GreenhouseComponent.cpp.
References children, and GreenhouseComponent().
getChildCount()
int GreenhouseComponent::getChildCount () const virtual
Gets the number of children this component has.
Returns
The count of child components (0 for leaf nodes)
Definition at line 36 of file GreenhouseComponent.cpp.
References children.
getName()
std::string GreenhouseComponent::getName () const
Gets the name of this component.
Returns
The component's name as a string
Definition at line 40 of file GreenhouseComponent.cpp.
References name.
Referenced by Greenhouse::display(), GreenhouseSection::display(), PlantLeaf::display(), and Shelf::display().
isComposite()
bool GreenhouseComponent::isComposite () const virtual
Checks if this component is a composite (has children)
Returns
true if this is a composite node, false if it's a leaf node
Default implementation returns false. Composite classes should override this to return true.
Reimplemented in Greenhouse, GreenhouseSection, PlantLeaf, and Shelf.
Definition at line 44 of file GreenhouseComponent.cpp.
remove()
void GreenhouseComponent::remove (GreenhouseComponent * component) virtual
Removes a child component from this component.
Parameters
component Pointer to the GreenhouseComponent to remove
Searches the children vector and removes the specified component if found. For leaf nodes, this operation typically does nothing.
Note
Does not delete the component object, only removes it from the children list
Reimplemented in PlantLeaf.
Definition at line 22 of file GreenhouseComponent.cpp.
References children, and GreenhouseComponent().
Member Data Documentation
children
std::vector<GreenhouseComponent*> GreenhouseComponent::children protected
Container for child components in the composite structure.
Stores pointers to child GreenhouseComponent objects. For leaf nodes, this vector remains empty. For composite nodes (Greenhouse, Section, Shelf), it contains their children.
Definition at line 42 of file GreenhouseComponent.h.
Referenced by add(), Greenhouse::display(), GreenhouseSection::display(), Shelf::display(), getChild(), getChildCount(), remove(), and ~GreenhouseComponent().
name
std::string GreenhouseComponent::name protected
Name identifier for this component.
Stores a descriptive name for the component (e.g., "Section A", "Rose Shelf", "Rose Plant #1")
Definition at line 49 of file GreenhouseComponent.h.
Referenced by getName(), Greenhouse::Greenhouse(), GreenhouseComponent(), GreenhouseSection::GreenhouseSection(), PlantLeaf::PlantLeaf(), and Shelf::Shelf().
The documentation for this class was generated from the following files:
Composite - The Store layout/GreenhouseComponent.h
Composite - The Store layout/GreenhouseComponent.cpp