NJD Films Greenhouse Management System: BasicPlant Class Reference
BasicPlant Class Reference
Concrete component representing an undecorated plant product.
#include <BasicPlant.h>
Public Member Functions
BasicPlant ()
Default constructor.
BasicPlant (Plant *p)
Constructor with plant parameter.
virtual ~BasicPlant ()
Virtual destructor.
double getPrice () const override
Gets the price of the basic plant.
std::string getDescription () const override
Gets the description of the basic plant.
void display () const override
Displays the basic plant information.
Public Member Functions inherited from PlantProduct
PlantProduct ()
Default constructor.
PlantProduct (Plant *p)
Constructor with plant parameter.
virtual ~PlantProduct ()
Virtual destructor.
Plant * getPlant () const
Gets the underlying plant object.
void setPlant (Plant *p)
Sets the underlying plant object.
Additional Inherited Members
Protected Attributes inherited from PlantProduct
Plant * plant
Pointer to the actual plant being sold.
Detailed Description
Concrete component representing an undecorated plant product.
BasicPlant serves as the ConcreteComponent in the Decorator design pattern. It represents a plain plant product without any additional decorations or features. This is the base object to which decorators can be applied to add features like decorative pots, gift wrapping, or greeting cards.
BasicPlant provides the simplest implementation of PlantProduct, returning the plant's base price and basic description without any embellishments. It acts as the core component that decorators wrap around.
Design Pattern Role:
ConcreteComponent: BasicPlant (this class)
Component: PlantProduct
Decorator: PlantDecorator
ConcreteDecorators: DecorativePotDecorator, GiftWrappingDecorator, etc.
Usage Example:
Plant* rose = new Rose();
PlantProduct* basicProduct = new BasicPlant(rose);
cout << "Price: R" << basicProduct->getPrice() << endl;  // Shows base plant price
// Can be wrapped with decorators:
PlantProduct* decoratedProduct = new DecorativePotDecorator(basicProduct);
cout << "Price: R" << decoratedProduct->getPrice() << endl;  // Shows base + pot price
See also
PlantProduct
PlantDecorator
DecorativePotDecorator
GiftWrappingDecorator
Plant
Definition at line 51 of file BasicPlant.h.
Constructor & Destructor Documentation
BasicPlant() [1/2]
BasicPlant::BasicPlant ()
Default constructor.
Creates a BasicPlant with no associated plant
Postcondition
BasicPlant object is created with nullptr plant
Definition at line 6 of file BasicPlant.cpp.
References PlantProduct::PlantProduct().
BasicPlant() [2/2]
BasicPlant::BasicPlant (Plant * p) explicit
Constructor with plant parameter.
Parameters
p Pointer to the Plant object to wrap
Creates a BasicPlant wrapping the specified plant. This is the typical way to create a basic plant product for sale.
Precondition
p should be a valid Plant pointer
Postcondition
BasicPlant is initialized with the given plant
Definition at line 8 of file BasicPlant.cpp.
References PlantProduct::PlantProduct().
~BasicPlant()
BasicPlant::~BasicPlant () virtual
Virtual destructor.
Cleans up the BasicPlant object
Note
Does not delete the wrapped plant - ownership remains with caller
Definition at line 10 of file BasicPlant.cpp.
Member Function Documentation
display()
void BasicPlant::display () const override virtual
Displays the basic plant information.
Outputs plant details to standard output
Displays the plant's basic information including species, type, and price in a user-friendly format. This is the undecorated display that shows only the plant's core information.
Postcondition
Plant information is displayed to standard output
Note
Output format is plain, without decorator additions
Implements PlantProduct.
Definition at line 26 of file BasicPlant.cpp.
References getDescription(), and getPrice().
getDescription()
std::string BasicPlant::getDescription () const override virtual
Gets the description of the basic plant.
Returns
Simple description of the plant without decoration details
Returns a basic description of the plant including its species and type, without any decorator embellishments.
Returns
String describing the basic plant
Postcondition
No modification to plant or product state
Note
If plant is nullptr, returns generic description
Implements PlantProduct.
Definition at line 19 of file BasicPlant.cpp.
References PlantProduct::plant.
Referenced by display().
getPrice()
double BasicPlant::getPrice () const override virtual
Gets the price of the basic plant.
Returns
The base price of the plant without any decorations
Returns the unmodified base price of the wrapped plant. This is the starting point for price calculations when decorators are applied.
Returns
Base price in currency units (R)
Postcondition
No modification to plant or product state
Note
If plant is nullptr, returns 0.0
Implements PlantProduct.
Definition at line 12 of file BasicPlant.cpp.
References PlantProduct::plant.
Referenced by display().
The documentation for this class was generated from the following files:
Decorator - Plant Decoration/BasicPlant.h
Decorator - Plant Decoration/BasicPlant.cpp