NJD Films Greenhouse Management System: PlantDecorator Class Reference
PlantDecorator Class Reference abstract
Abstract decorator class for adding features to plant products.
#include <PlantDecorator.h>
Public Member Functions
PlantDecorator ()
Default constructor.
PlantDecorator (PlantProduct *product)
Constructor with product parameter.
virtual ~PlantDecorator ()
Virtual destructor.
virtual double getPrice () const override=0
Pure virtual method to get decorated price.
virtual std::string getDescription () const override=0
Pure virtual method to get decorated description.
virtual void display () const override
Displays the decorated product information.
PlantProduct * getWrappedProduct () const
Gets the wrapped product reference.
void setWrappedProduct (PlantProduct *product)
Sets the wrapped product reference.
Public Member Functions inherited from PlantProduct
PlantProduct ()
Default constructor.
PlantProduct (Plant *p)
Constructor with plant parameter.
virtual ~PlantProduct ()
Virtual destructor.
Plant * getPlant () const
Gets the underlying plant object.
void setPlant (Plant *p)
Sets the underlying plant object.
Protected Attributes
PlantProduct * wrappedProduct
Pointer to the wrapped product being decorated.
Protected Attributes inherited from PlantProduct
Plant * plant
Pointer to the actual plant being sold.
Detailed Description
Abstract decorator class for adding features to plant products.
PlantDecorator serves as the Decorator in the Decorator design pattern. It wraps a PlantProduct (either a BasicPlant or another decorator) and provides a base for concrete decorators to add additional features like decorative pots, gift wrapping, or greeting cards.
This class maintains a reference to the wrapped product and delegates operations to it while allowing subclasses to enhance or modify the behavior. It provides the foundation for the transparent decoration of plant products.
PlantDecorator inherits from PlantProduct, making it interchangeable with the objects it decorates. This allows decorators to be nested, creating complex combinations of features.
Design Pattern Role:
Decorator: PlantDecorator (this class)
Component: PlantProduct
ConcreteComponent: BasicPlant
ConcreteDecorators: DecorativePotDecorator, GiftWrappingDecorator, GreetingCardDecorator
Key Decorator Pattern Features:
Wraps a PlantProduct reference
Maintains same interface as PlantProduct
Allows dynamic addition of responsibilities
Enables decorator nesting/stacking
Usage Example:
PlantProduct* product = new BasicPlant(rose);
product = new DecorativePotDecorator(product);  // Add pot
product = new GiftWrappingDecorator(product);   // Add wrapping
product = new GreetingCardDecorator(product);   // Add card
cout << "Total: R" << product->getPrice() << endl;
See also
PlantProduct
BasicPlant
DecorativePotDecorator
GiftWrappingDecorator
GreetingCardDecorator
Definition at line 60 of file PlantDecorator.h.
Constructor & Destructor Documentation
PlantDecorator() [1/2]
PlantDecorator::PlantDecorator ()
Default constructor.
Creates a decorator with no wrapped product
Postcondition
PlantDecorator is created with nullptr wrappedProduct
Definition at line 6 of file PlantDecorator.cpp.
References PlantProduct::PlantProduct(), and wrappedProduct.
Referenced by DecorativePotDecorator::DecorativePotDecorator(), DecorativePotDecorator::DecorativePotDecorator(), GiftWrappingDecorator::GiftWrappingDecorator(), GiftWrappingDecorator::GiftWrappingDecorator(), GreetingCardDecorator::GreetingCardDecorator(), and GreetingCardDecorator::GreetingCardDecorator().
PlantDecorator() [2/2]
PlantDecorator::PlantDecorator (PlantProduct * product) explicit
Constructor with product parameter.
Parameters
product Pointer to the PlantProduct to wrap/decorate
Creates a decorator that wraps the specified product. This is the typical way decorators are constructed.
Precondition
product should be a valid PlantProduct pointer
Postcondition
PlantDecorator is initialized wrapping the given product
Definition at line 8 of file PlantDecorator.cpp.
References PlantProduct::getPlant(), PlantProduct::PlantProduct(), and wrappedProduct.
~PlantDecorator()
PlantDecorator::~PlantDecorator () virtual
Virtual destructor.
Ensures proper cleanup of decorator objects
Note
Does not delete wrappedProduct - ownership chain must be managed by the client code
Definition at line 12 of file PlantDecorator.cpp.
Member Function Documentation
display()
void PlantDecorator::display () const override virtual
Displays the decorated product information.
Default implementation delegates to wrapped product
Outputs the complete product information including all nested decorations. Can be overridden by concrete decorators for custom display formatting.
Postcondition
Product information with all decorations is displayed
Note
Default delegates to wrappedProduct->display()
Implements PlantProduct.
Reimplemented in DecorativePotDecorator, GiftWrappingDecorator, and GreetingCardDecorator.
Definition at line 27 of file PlantDecorator.cpp.
References getDescription(), getPrice(), and wrappedProduct.
getDescription()
virtual std::string PlantDecorator::getDescription () const override pure virtual
Pure virtual method to get decorated description.
Returns
Complete description including this decorator's addition
Must be implemented by concrete decorators. Typically returns wrappedProduct->getDescription() + decorator's description.
Note
Concrete decorators implement: return wrapped->getDescription() + myDesc
Warning
Must be implemented by all concrete decorator classes
Implements PlantProduct.
Implemented in DecorativePotDecorator, GiftWrappingDecorator, and GreetingCardDecorator.
References PlantProduct::PlantProduct().
Referenced by display().
getPrice()
virtual double PlantDecorator::getPrice () const override pure virtual
Pure virtual method to get decorated price.
Returns
Total price including this decorator's cost
Must be implemented by concrete decorators. Typically returns wrappedProduct->getPrice() + decorator's additional cost.
Note
Concrete decorators implement: return wrapped->getPrice() + myCost
Warning
Must be implemented by all concrete decorator classes
Implements PlantProduct.
Implemented in DecorativePotDecorator, GiftWrappingDecorator, and GreetingCardDecorator.
Referenced by display().
getWrappedProduct()
PlantProduct * PlantDecorator::getWrappedProduct () const
Gets the wrapped product reference.
Returns
Pointer to the wrapped PlantProduct
Provides access to the product this decorator wraps. Useful for accessing the decoration chain or unwrapping decorators.
Returns
Pointer to wrapped PlantProduct, or nullptr if none
Note
Returned pointer should not be deleted by caller
Definition at line 16 of file PlantDecorator.cpp.
References PlantProduct::PlantProduct(), and wrappedProduct.
setWrappedProduct()
void PlantDecorator::setWrappedProduct (PlantProduct * product)
Sets the wrapped product reference.
Parameters
product Pointer to the PlantProduct to wrap
Allows changing the product this decorator wraps. Use with caution as it can break the decoration chain.
Precondition
product should be a valid PlantProduct pointer
Postcondition
wrappedProduct is updated to point to product
Note
Previous wrapped product is not deleted
Warning
Does not transfer ownership
Definition at line 20 of file PlantDecorator.cpp.
References PlantProduct::getPlant(), PlantProduct::plant, PlantProduct::PlantProduct(), and wrappedProduct.
Member Data Documentation
wrappedProduct
PlantProduct* PlantDecorator::wrappedProduct protected
Pointer to the wrapped product being decorated.
Maintains reference to the PlantProduct this decorator enhances
Definition at line 66 of file PlantDecorator.h.
Referenced by DecorativePotDecorator::display(), GiftWrappingDecorator::display(), GreetingCardDecorator::display(), display(), DecorativePotDecorator::getDescription(), GiftWrappingDecorator::getDescription(), GreetingCardDecorator::getDescription(), DecorativePotDecorator::getPrice(), GiftWrappingDecorator::getPrice(), GreetingCardDecorator::getPrice(), getWrappedProduct(), PlantDecorator(), PlantDecorator(), and setWrappedProduct().
The documentation for this class was generated from the following files:
Decorator - Plant Decoration/PlantDecorator.h
Decorator - Plant Decoration/PlantDecorator.cpp